// AUTO-GENERATED by scripts/optimize-images.mts — do not edit by hand.
// Curated real-event photography for the editorial design system.

export type CuratedImage = {
  src: string;
  srcSet: Record<string, string>;
  width: number;
  height: number;
  role: "hero" | "divider" | "card" | "support";
  alt: string;
};

export const curatedImages = {
  "hero-conference-crowd": {
    src: "/img/curated/hero-conference-crowd-1920.webp",
    srcSet: {
      "1920": "/img/curated/hero-conference-crowd-1920.webp",
      "1280": "/img/curated/hero-conference-crowd-1280.webp",
      "768": "/img/curated/hero-conference-crowd-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "hero",
    alt: "Large group of She Sharp community members gathered together at a technology conference, smiling for a group photo.",
  },
  "hero-thrive-speaker": {
    src: "/img/curated/hero-thrive-speaker-1920.webp",
    srcSet: {
      "1920": "/img/curated/hero-thrive-speaker-1920.webp",
      "1280": "/img/curated/hero-thrive-speaker-1280.webp",
      "768": "/img/curated/hero-thrive-speaker-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "hero",
    alt: "A speaker addresses a She Sharp audience in a darkened room, standing before a large screen reading THRIVE: Your Career, Your Story.",
  },
  "hero-celebration-handsup": {
    src: "/img/curated/hero-celebration-handsup-1920.webp",
    srcSet: {
      "1920": "/img/curated/hero-celebration-handsup-1920.webp",
      "1280": "/img/curated/hero-celebration-handsup-1280.webp",
      "768": "/img/curated/hero-celebration-handsup-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "hero",
    alt: "A room full of She Sharp attendees cheering with their hands raised in celebration.",
  },
  "hero-community-cheer": {
    src: "/img/curated/hero-community-cheer-1920.webp",
    srcSet: {
      "1920": "/img/curated/hero-community-cheer-1920.webp",
      "1280": "/img/curated/hero-community-cheer-1280.webp",
      "768": "/img/curated/hero-community-cheer-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "hero",
    alt: "A large, diverse crowd of She Sharp members celebrating together at a community event.",
  },
  "hero-anniversary-crowd": {
    src: "/img/curated/hero-anniversary-crowd-1920.webp",
    srcSet: {
      "1920": "/img/curated/hero-anniversary-crowd-1920.webp",
      "1280": "/img/curated/hero-anniversary-crowd-1280.webp",
      "768": "/img/curated/hero-anniversary-crowd-768.webp",
    },
    width: 1920,
    height: 1039,
    role: "hero",
    alt: "A wide shot of the She Sharp community celebrating an anniversary milestone with arms raised.",
  },
  "divider-crowd-wide": {
    src: "/img/curated/divider-crowd-wide-1920.webp",
    srcSet: {
      "1920": "/img/curated/divider-crowd-wide-1920.webp",
      "1280": "/img/curated/divider-crowd-wide-1280.webp",
      "768": "/img/curated/divider-crowd-wide-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "divider",
    alt: "A large group of She Sharp event attendees posed together in a bright venue.",
  },
  "divider-community-room": {
    src: "/img/curated/divider-community-room-1920.webp",
    srcSet: {
      "1920": "/img/curated/divider-community-room-1920.webp",
      "1280": "/img/curated/divider-community-room-1280.webp",
      "768": "/img/curated/divider-community-room-768.webp",
    },
    width: 1920,
    height: 1025,
    role: "divider",
    alt: "Attendees gathered across a wide event space for a She Sharp community group photo.",
  },
  "divider-group-warm": {
    src: "/img/curated/divider-group-warm-1920.webp",
    srcSet: {
      "1920": "/img/curated/divider-group-warm-1920.webp",
      "1280": "/img/curated/divider-group-warm-1280.webp",
      "768": "/img/curated/divider-group-warm-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "divider",
    alt: "She Sharp attendees seated and standing together for a group photo at a partner venue.",
  },
  "divider-city-backdrop": {
    src: "/img/curated/divider-city-backdrop-1920.webp",
    srcSet: {
      "1920": "/img/curated/divider-city-backdrop-1920.webp",
      "1280": "/img/curated/divider-city-backdrop-1280.webp",
      "768": "/img/curated/divider-city-backdrop-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "divider",
    alt: "A She Sharp group photographed in front of large windows overlooking a city skyline.",
  },
  "divider-standing-group": {
    src: "/img/curated/divider-standing-group-1920.webp",
    srcSet: {
      "1920": "/img/curated/divider-standing-group-1920.webp",
      "1280": "/img/curated/divider-standing-group-1280.webp",
      "768": "/img/curated/divider-standing-group-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "divider",
    alt: "Attendees standing together at a She Sharp event beneath a From Burnout to Balance screen.",
  },
  "speaker-stage-spotlight": {
    src: "/img/curated/speaker-stage-spotlight-1920.webp",
    srcSet: {
      "1920": "/img/curated/speaker-stage-spotlight-1920.webp",
      "1280": "/img/curated/speaker-stage-spotlight-1280.webp",
      "768": "/img/curated/speaker-stage-spotlight-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "A She Sharp speaker presenting from a podium on a darkened stage.",
  },
  "panel-fireside-chat": {
    src: "/img/curated/panel-fireside-chat-1920.webp",
    srcSet: {
      "1920": "/img/curated/panel-fireside-chat-1920.webp",
      "1280": "/img/curated/panel-fireside-chat-1280.webp",
      "768": "/img/curated/panel-fireside-chat-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "A panel of women seated in armchairs during a She Sharp fireside discussion.",
  },
  "panel-discussion": {
    src: "/img/curated/panel-discussion-1920.webp",
    srcSet: {
      "1920": "/img/curated/panel-discussion-1920.webp",
      "1280": "/img/curated/panel-discussion-1280.webp",
      "768": "/img/curated/panel-discussion-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "Panellists in conversation on stage during a She Sharp women in tech discussion.",
  },
  "panel-mic-moment": {
    src: "/img/curated/panel-mic-moment-1920.webp",
    srcSet: {
      "1920": "/img/curated/panel-mic-moment-1920.webp",
      "1280": "/img/curated/panel-mic-moment-1280.webp",
      "768": "/img/curated/panel-mic-moment-768.webp",
    },
    width: 1920,
    height: 1088,
    role: "card",
    alt: "A panellist speaking into a microphone during a She Sharp panel session.",
  },
  "speaker-audience": {
    src: "/img/curated/speaker-audience-1920.webp",
    srcSet: {
      "1920": "/img/curated/speaker-audience-1920.webp",
      "1280": "/img/curated/speaker-audience-1280.webp",
      "768": "/img/curated/speaker-audience-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "A presenter welcoming a seated audience at the start of a She Sharp event.",
  },
  "workshop-team-build": {
    src: "/img/curated/workshop-team-build-1920.webp",
    srcSet: {
      "1878": "/img/curated/workshop-team-build-1920.webp",
      "1280": "/img/curated/workshop-team-build-1280.webp",
      "768": "/img/curated/workshop-team-build-768.webp",
    },
    width: 1878,
    height: 1270,
    role: "card",
    alt: "A diverse team smiling around a hands-on build challenge during a She Sharp workshop.",
  },
  "workshop-tower-focus": {
    src: "/img/curated/workshop-tower-focus-1920.webp",
    srcSet: {
      "1920": "/img/curated/workshop-tower-focus-1920.webp",
      "1280": "/img/curated/workshop-tower-focus-1280.webp",
      "768": "/img/curated/workshop-tower-focus-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "Two participants concentrating as they build a structure together at a She Sharp workshop.",
  },
  "workshop-hands-on": {
    src: "/img/curated/workshop-hands-on-1920.webp",
    srcSet: {
      "1920": "/img/curated/workshop-hands-on-1920.webp",
      "1280": "/img/curated/workshop-hands-on-1280.webp",
      "768": "/img/curated/workshop-hands-on-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "Participants working hands-on with craft materials during a She Sharp workshop activity.",
  },
  "workshop-collaboration": {
    src: "/img/curated/workshop-collaboration-1920.webp",
    srcSet: {
      "1920": "/img/curated/workshop-collaboration-1920.webp",
      "1280": "/img/curated/workshop-collaboration-1280.webp",
      "768": "/img/curated/workshop-collaboration-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "Attendees collaborating around a table during a She Sharp workshop session.",
  },
  "mentoring-huddle": {
    src: "/img/curated/mentoring-huddle-1920.webp",
    srcSet: {
      "1920": "/img/curated/mentoring-huddle-1920.webp",
      "1280": "/img/curated/mentoring-huddle-1280.webp",
      "768": "/img/curated/mentoring-huddle-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "A small group looking at a tablet together during a She Sharp mentoring moment.",
  },
  "detail-sketch-hands": {
    src: "/img/curated/detail-sketch-hands-1920.webp",
    srcSet: {
      "1920": "/img/curated/detail-sketch-hands-1920.webp",
      "1280": "/img/curated/detail-sketch-hands-1280.webp",
      "768": "/img/curated/detail-sketch-hands-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "support",
    alt: "Close-up of a hand sketching ideas on paper during a She Sharp session.",
  },
  "connection-smiles": {
    src: "/img/curated/connection-smiles-1920.webp",
    srcSet: {
      "1920": "/img/curated/connection-smiles-1920.webp",
      "1280": "/img/curated/connection-smiles-1280.webp",
      "768": "/img/curated/connection-smiles-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "Three She Sharp attendees smiling together at an event.",
  },
  "celebration-group-smiles": {
    src: "/img/curated/celebration-group-smiles-1920.webp",
    srcSet: {
      "1873": "/img/curated/celebration-group-smiles-1920.webp",
      "1280": "/img/curated/celebration-group-smiles-1280.webp",
      "768": "/img/curated/celebration-group-smiles-768.webp",
    },
    width: 1873,
    height: 1061,
    role: "card",
    alt: "A group of smiling women wearing event lanyards at a She Sharp gathering.",
  },
  "celebration-swag-bags": {
    src: "/img/curated/celebration-swag-bags-1920.webp",
    srcSet: {
      "1920": "/img/curated/celebration-swag-bags-1920.webp",
      "1280": "/img/curated/celebration-swag-bags-1280.webp",
      "768": "/img/curated/celebration-swag-bags-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "Attendees holding up colourful She Sharp tote bags at an event.",
  },
  "celebration-awards": {
    src: "/img/curated/celebration-awards-1920.webp",
    srcSet: {
      "1920": "/img/curated/celebration-awards-1920.webp",
      "1280": "/img/curated/celebration-awards-1280.webp",
      "768": "/img/curated/celebration-awards-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "A She Sharp group holding awards together at a recognition event.",
  },
} as const satisfies Record<string, CuratedImage>;

export type CuratedImageKey = keyof typeof curatedImages;

/** Build a `srcSet` attribute string (width descriptors) from a curated entry. */
export function toSrcSet(img: CuratedImage): string {
  return Object.entries(img.srcSet)
    .map(([w, url]) => `${url} ${w}w`)
    .join(", ");
}
