// AUTO-GENERATED by scripts/optimize-images.mts — do not edit by hand.
// Curated real-event photography for the editorial design system.

export type CuratedImage = {
  src: string;
  srcSet: Record<string, string>;
  width: number;
  height: number;
  role: "hero" | "divider" | "card" | "support";
  alt: string;
};

export const curatedImages = {
  "hero-conference-crowd": {
    src: "/img/curated/hero-conference-crowd-1920.webp",
    srcSet: {
      "1920": "/img/curated/hero-conference-crowd-1920.webp",
      "1280": "/img/curated/hero-conference-crowd-1280.webp",
      "768": "/img/curated/hero-conference-crowd-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "hero",
    alt: "Large group of She Sharp community members gathered together at a technology conference, smiling for a group photo.",
  },
  "hero-thrive-speaker": {
    src: "/img/curated/hero-thrive-speaker-1920.webp",
    srcSet: {
      "1920": "/img/curated/hero-thrive-speaker-1920.webp",
      "1280": "/img/curated/hero-thrive-speaker-1280.webp",
      "768": "/img/curated/hero-thrive-speaker-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "hero",
    alt: "A speaker addresses a She Sharp audience in a darkened room, standing before a large screen reading THRIVE: Your Career, Your Story.",
  },
  "hero-celebration-handsup": {
    src: "/img/curated/hero-celebration-handsup-1920.webp",
    srcSet: {
      "1920": "/img/curated/hero-celebration-handsup-1920.webp",
      "1280": "/img/curated/hero-celebration-handsup-1280.webp",
      "768": "/img/curated/hero-celebration-handsup-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "hero",
    alt: "A room full of She Sharp attendees cheering with their hands raised in celebration.",
  },
  "hero-community-cheer": {
    src: "/img/curated/hero-community-cheer-1920.webp",
    srcSet: {
      "1920": "/img/curated/hero-community-cheer-1920.webp",
      "1280": "/img/curated/hero-community-cheer-1280.webp",
      "768": "/img/curated/hero-community-cheer-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "hero",
    alt: "A large, diverse crowd of She Sharp members celebrating together at a community event.",
  },
  "hero-anniversary-crowd": {
    src: "/img/curated/hero-anniversary-crowd-1920.webp",
    srcSet: {
      "1920": "/img/curated/hero-anniversary-crowd-1920.webp",
      "1280": "/img/curated/hero-anniversary-crowd-1280.webp",
      "768": "/img/curated/hero-anniversary-crowd-768.webp",
    },
    width: 1920,
    height: 1039,
    role: "hero",
    alt: "A wide shot of the She Sharp community celebrating an anniversary milestone with arms raised.",
  },
  "divider-crowd-wide": {
    src: "/img/curated/divider-crowd-wide-1920.webp",
    srcSet: {
      "1920": "/img/curated/divider-crowd-wide-1920.webp",
      "1280": "/img/curated/divider-crowd-wide-1280.webp",
      "768": "/img/curated/divider-crowd-wide-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "divider",
    alt: "A large group of She Sharp event attendees posed together in a bright venue.",
  },
  "divider-community-room": {
    src: "/img/curated/divider-community-room-1920.webp",
    srcSet: {
      "1920": "/img/curated/divider-community-room-1920.webp",
      "1280": "/img/curated/divider-community-room-1280.webp",
      "768": "/img/curated/divider-community-room-768.webp",
    },
    width: 1920,
    height: 1025,
    role: "divider",
    alt: "Attendees gathered across a wide event space for a She Sharp community group photo.",
  },
  "divider-group-warm": {
    src: "/img/curated/divider-group-warm-1920.webp",
    srcSet: {
      "1920": "/img/curated/divider-group-warm-1920.webp",
      "1280": "/img/curated/divider-group-warm-1280.webp",
      "768": "/img/curated/divider-group-warm-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "divider",
    alt: "She Sharp attendees seated and standing together for a group photo at a partner venue.",
  },
  "divider-city-backdrop": {
    src: "/img/curated/divider-city-backdrop-1920.webp",
    srcSet: {
      "1920": "/img/curated/divider-city-backdrop-1920.webp",
      "1280": "/img/curated/divider-city-backdrop-1280.webp",
      "768": "/img/curated/divider-city-backdrop-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "divider",
    alt: "A She Sharp group photographed in front of large windows overlooking a city skyline.",
  },
  "divider-standing-group": {
    src: "/img/curated/divider-standing-group-1920.webp",
    srcSet: {
      "1920": "/img/curated/divider-standing-group-1920.webp",
      "1280": "/img/curated/divider-standing-group-1280.webp",
      "768": "/img/curated/divider-standing-group-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "divider",
    alt: "Attendees standing together at a She Sharp event beneath a From Burnout to Balance screen.",
  },
  "speaker-stage-spotlight": {
    src: "/img/curated/speaker-stage-spotlight-1920.webp",
    srcSet: {
      "1920": "/img/curated/speaker-stage-spotlight-1920.webp",
      "1280": "/img/curated/speaker-stage-spotlight-1280.webp",
      "768": "/img/curated/speaker-stage-spotlight-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "A She Sharp speaker presenting from a podium on a darkened stage.",
  },
  "panel-fireside-chat": {
    src: "/img/curated/panel-fireside-chat-1920.webp",
    srcSet: {
      "1920": "/img/curated/panel-fireside-chat-1920.webp",
      "1280": "/img/curated/panel-fireside-chat-1280.webp",
      "768": "/img/curated/panel-fireside-chat-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "A panel of women seated in armchairs during a She Sharp fireside discussion.",
  },
  "panel-discussion": {
    src: "/img/curated/panel-discussion-1920.webp",
    srcSet: {
      "1920": "/img/curated/panel-discussion-1920.webp",
      "1280": "/img/curated/panel-discussion-1280.webp",
      "768": "/img/curated/panel-discussion-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "Panellists in conversation on stage during a She Sharp women in tech discussion.",
  },
  "panel-mic-moment": {
    src: "/img/curated/panel-mic-moment-1920.webp",
    srcSet: {
      "1920": "/img/curated/panel-mic-moment-1920.webp",
      "1280": "/img/curated/panel-mic-moment-1280.webp",
      "768": "/img/curated/panel-mic-moment-768.webp",
    },
    width: 1920,
    height: 1088,
    role: "card",
    alt: "A panellist speaking into a microphone during a She Sharp panel session.",
  },
  "speaker-audience": {
    src: "/img/curated/speaker-audience-1920.webp",
    srcSet: {
      "1920": "/img/curated/speaker-audience-1920.webp",
      "1280": "/img/curated/speaker-audience-1280.webp",
      "768": "/img/curated/speaker-audience-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "A presenter welcoming a seated audience at the start of a She Sharp event.",
  },
  "workshop-team-build": {
    src: "/img/curated/workshop-team-build-1920.webp",
    srcSet: {
      "1878": "/img/curated/workshop-team-build-1920.webp",
      "1280": "/img/curated/workshop-team-build-1280.webp",
      "768": "/img/curated/workshop-team-build-768.webp",
    },
    width: 1878,
    height: 1270,
    role: "card",
    alt: "A diverse team smiling around a hands-on build challenge during a She Sharp workshop.",
  },
  "workshop-tower-focus": {
    src: "/img/curated/workshop-tower-focus-1920.webp",
    srcSet: {
      "1920": "/img/curated/workshop-tower-focus-1920.webp",
      "1280": "/img/curated/workshop-tower-focus-1280.webp",
      "768": "/img/curated/workshop-tower-focus-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "Two participants concentrating as they build a structure together at a She Sharp workshop.",
  },
  "workshop-hands-on": {
    src: "/img/curated/workshop-hands-on-1920.webp",
    srcSet: {
      "1920": "/img/curated/workshop-hands-on-1920.webp",
      "1280": "/img/curated/workshop-hands-on-1280.webp",
      "768": "/img/curated/workshop-hands-on-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "Participants working hands-on with craft materials during a She Sharp workshop activity.",
  },
  "workshop-collaboration": {
    src: "/img/curated/workshop-collaboration-1920.webp",
    srcSet: {
      "1920": "/img/curated/workshop-collaboration-1920.webp",
      "1280": "/img/curated/workshop-collaboration-1280.webp",
      "768": "/img/curated/workshop-collaboration-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "Attendees collaborating around a table during a She Sharp workshop session.",
  },
  "mentoring-huddle": {
    src: "/img/curated/mentoring-huddle-1920.webp",
    srcSet: {
      "1920": "/img/curated/mentoring-huddle-1920.webp",
      "1280": "/img/curated/mentoring-huddle-1280.webp",
      "768": "/img/curated/mentoring-huddle-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "A small group looking at a tablet together during a She Sharp mentoring moment.",
  },
  "detail-sketch-hands": {
    src: "/img/curated/detail-sketch-hands-1920.webp",
    srcSet: {
      "1920": "/img/curated/detail-sketch-hands-1920.webp",
      "1280": "/img/curated/detail-sketch-hands-1280.webp",
      "768": "/img/curated/detail-sketch-hands-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "support",
    alt: "Close-up of a hand sketching ideas on paper during a She Sharp session.",
  },
  "connection-smiles": {
    src: "/img/curated/connection-smiles-1920.webp",
    srcSet: {
      "1920": "/img/curated/connection-smiles-1920.webp",
      "1280": "/img/curated/connection-smiles-1280.webp",
      "768": "/img/curated/connection-smiles-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "Three She Sharp attendees smiling together at an event.",
  },
  "celebration-group-smiles": {
    src: "/img/curated/celebration-group-smiles-1920.webp",
    srcSet: {
      "1873": "/img/curated/celebration-group-smiles-1920.webp",
      "1280": "/img/curated/celebration-group-smiles-1280.webp",
      "768": "/img/curated/celebration-group-smiles-768.webp",
    },
    width: 1873,
    height: 1061,
    role: "card",
    alt: "A group of smiling women wearing event lanyards at a She Sharp gathering.",
  },
  "celebration-swag-bags": {
    src: "/img/curated/celebration-swag-bags-1920.webp",
    srcSet: {
      "1920": "/img/curated/celebration-swag-bags-1920.webp",
      "1280": "/img/curated/celebration-swag-bags-1280.webp",
      "768": "/img/curated/celebration-swag-bags-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "Attendees holding up colourful She Sharp tote bags at an event.",
  },
  "celebration-awards": {
    src: "/img/curated/celebration-awards-1920.webp",
    srcSet: {
      "1920": "/img/curated/celebration-awards-1920.webp",
      "1280": "/img/curated/celebration-awards-1280.webp",
      "768": "/img/curated/celebration-awards-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "A She Sharp group holding awards together at a recognition event.",
  },
  "hero-inspire-her-crowd": {
    src: "/img/curated/hero-inspire-her-crowd-1920.webp",
    srcSet: {
      "1920": "/img/curated/hero-inspire-her-crowd-1920.webp",
      "1280": "/img/curated/hero-inspire-her-crowd-1280.webp",
      "768": "/img/curated/hero-inspire-her-crowd-768.webp",
    },
    width: 1920,
    height: 1026,
    role: "hero",
    alt: "A large gathering of the She Sharp community posed together in rows for a group photo at the Inspire Her event, many wearing pink lanyards.",
  },
  "divider-educator-conference": {
    src: "/img/curated/divider-educator-conference-1920.webp",
    srcSet: {
      "1920": "/img/curated/divider-educator-conference-1920.webp",
      "1280": "/img/curated/divider-educator-conference-1280.webp",
      "768": "/img/curated/divider-educator-conference-768.webp",
    },
    width: 1920,
    height: 1002,
    role: "divider",
    alt: "A large, diverse group of She Sharp attendees standing and kneeling together for a group photo at the Google Educator Conference.",
  },
  "divider-trademe-group": {
    src: "/img/curated/divider-trademe-group-1920.webp",
    srcSet: {
      "1920": "/img/curated/divider-trademe-group-1920.webp",
      "1280": "/img/curated/divider-trademe-group-1280.webp",
      "768": "/img/curated/divider-trademe-group-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "divider",
    alt: "The She Sharp community gathered in tiered rows for a group photo in front of a lush green living wall at a Trade Me event.",
  },
  "divider-aws-community": {
    src: "/img/curated/divider-aws-community-1920.webp",
    srcSet: {
      "1920": "/img/curated/divider-aws-community-1920.webp",
      "1280": "/img/curated/divider-aws-community-1280.webp",
      "768": "/img/curated/divider-aws-community-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "divider",
    alt: "A group of She Sharp members gathered together, seated and standing, in a warmly lit lounge at an Amazon Web Services event.",
  },
  "hero-diwali-community": {
    src: "/img/curated/hero-diwali-community-1920.webp",
    srcSet: {
      "1920": "/img/curated/hero-diwali-community-1920.webp",
      "1280": "/img/curated/hero-diwali-community-1280.webp",
      "768": "/img/curated/hero-diwali-community-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "hero",
    alt: "A large group in colourful traditional dress gathered for a group photo, with decorative parasols arranged in front, celebrating cultural diversity at a She Sharp event.",
  },
  "divider-venue-glasshouse": {
    src: "/img/curated/divider-venue-glasshouse-1920.webp",
    srcSet: {
      "1920": "/img/curated/divider-venue-glasshouse-1920.webp",
      "1280": "/img/curated/divider-venue-glasshouse-1280.webp",
      "768": "/img/curated/divider-venue-glasshouse-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "divider",
    alt: "A She Sharp gathering in a bright, glass-walled venue overlooking greenery, with attendees seated at round tables facing a presenter.",
  },
  "speaker-inspire-her": {
    src: "/img/curated/speaker-inspire-her-1920.webp",
    srcSet: {
      "1920": "/img/curated/speaker-inspire-her-1920.webp",
      "1280": "/img/curated/speaker-inspire-her-1280.webp",
      "768": "/img/curated/speaker-inspire-her-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "A speaker addressing the audience with a microphone at the She Sharp Inspire Her event, wearing a pink lanyard.",
  },
  "speaker-her-waka": {
    src: "/img/curated/speaker-her-waka-1920.webp",
    srcSet: {
      "1920": "/img/curated/speaker-her-waka-1920.webp",
      "1280": "/img/curated/speaker-her-waka-1280.webp",
      "768": "/img/curated/speaker-her-waka-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "A She Sharp presenter speaking and gesturing beside a screen showing the Her Waka session agenda.",
  },
  "speaker-own-your-energy": {
    src: "/img/curated/speaker-own-your-energy-1920.webp",
    srcSet: {
      "1920": "/img/curated/speaker-own-your-energy-1920.webp",
      "1280": "/img/curated/speaker-own-your-energy-1280.webp",
      "768": "/img/curated/speaker-own-your-energy-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "A presenter leading the Own Your Energy workshop at the front of the room before a seated She Sharp audience.",
  },
  "panel-her-waka": {
    src: "/img/curated/panel-her-waka-1920.webp",
    srcSet: {
      "1920": "/img/curated/panel-her-waka-1920.webp",
      "1280": "/img/curated/panel-her-waka-1280.webp",
      "768": "/img/curated/panel-her-waka-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "A panel of three speakers seated on stage during a She Sharp Her Waka session, with a presentation screen behind them.",
  },
  "panel-women-in-ai": {
    src: "/img/curated/panel-women-in-ai-1920.webp",
    srcSet: {
      "1920": "/img/curated/panel-women-in-ai-1920.webp",
      "1280": "/img/curated/panel-women-in-ai-1280.webp",
      "768": "/img/curated/panel-women-in-ai-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "Panellists seated on stage during a She Sharp women in AI discussion, facing a seated audience beside Women in Tech banners.",
  },
  "fireside-centrality": {
    src: "/img/curated/fireside-centrality-1920.webp",
    srcSet: {
      "1920": "/img/curated/fireside-centrality-1920.webp",
      "1280": "/img/curated/fireside-centrality-1280.webp",
      "768": "/img/curated/fireside-centrality-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "A speaker gesturing while addressing a small group seated on couches during an intimate She Sharp fireside session.",
  },
  "workshop-design-thinking": {
    src: "/img/curated/workshop-design-thinking-1920.webp",
    srcSet: {
      "1920": "/img/curated/workshop-design-thinking-1920.webp",
      "1280": "/img/curated/workshop-design-thinking-1280.webp",
      "768": "/img/curated/workshop-design-thinking-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "Two participants working together at a laptop during a She Sharp design-thinking workshop, with a countdown timer on the screen behind them.",
  },
  "workshop-girls-night-build": {
    src: "/img/curated/workshop-girls-night-build-1920.webp",
    srcSet: {
      "1920": "/img/curated/workshop-girls-night-build-1920.webp",
      "1280": "/img/curated/workshop-girls-night-build-1280.webp",
      "768": "/img/curated/workshop-girls-night-build-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "Participants leaning in together to build a spaghetti-and-tape tower during a hands-on She Sharp workshop challenge.",
  },
  "workshop-rpa-laughter": {
    src: "/img/curated/workshop-rpa-laughter-1920.webp",
    srcSet: {
      "1920": "/img/curated/workshop-rpa-laughter-1920.webp",
      "1280": "/img/curated/workshop-rpa-laughter-1280.webp",
      "768": "/img/curated/workshop-rpa-laughter-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "Three She Sharp attendees laughing together around a laptop during a robotic process automation session.",
  },
  "workshop-fp-hackathon": {
    src: "/img/curated/workshop-fp-hackathon-1920.webp",
    srcSet: {
      "1920": "/img/curated/workshop-fp-hackathon-1920.webp",
      "1280": "/img/curated/workshop-fp-hackathon-1280.webp",
      "768": "/img/curated/workshop-fp-hackathon-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "Participants collaborating over materials at a long table during a She Sharp hackathon working session.",
  },
  "audience-centrality-laughter": {
    src: "/img/curated/audience-centrality-laughter-1920.webp",
    srcSet: {
      "1920": "/img/curated/audience-centrality-laughter-1920.webp",
      "1280": "/img/curated/audience-centrality-laughter-1280.webp",
      "768": "/img/curated/audience-centrality-laughter-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "Four young women laughing together while seated during a She Sharp event.",
  },
  "audience-inspire-her-theatre": {
    src: "/img/curated/audience-inspire-her-theatre-1920.webp",
    srcSet: {
      "1920": "/img/curated/audience-inspire-her-theatre-1920.webp",
      "1280": "/img/curated/audience-inspire-her-theatre-1280.webp",
      "768": "/img/curated/audience-inspire-her-theatre-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "Young attendees seated in red theatre seats, listening attentively during the She Sharp Inspire Her event.",
  },
  "celebration-anniversary-booth": {
    src: "/img/curated/celebration-anniversary-booth-1920.webp",
    srcSet: {
      "1920": "/img/curated/celebration-anniversary-booth-1920.webp",
      "1280": "/img/curated/celebration-anniversary-booth-1280.webp",
      "768": "/img/curated/celebration-anniversary-booth-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "Attendees posing playfully with novelty glasses at a pink floral photo-booth wall during She Sharp's 10-year anniversary celebration.",
  },
  "celebration-imagine-zone": {
    src: "/img/curated/celebration-imagine-zone-1920.webp",
    srcSet: {
      "1920": "/img/curated/celebration-imagine-zone-1920.webp",
      "1280": "/img/curated/celebration-imagine-zone-1280.webp",
      "768": "/img/curated/celebration-imagine-zone-768.webp",
    },
    width: 1920,
    height: 1440,
    role: "card",
    alt: "A group gathered on the floor in front of a stage decorated with rainbow balloons and bunting at the She Sharp Imagine Zone event.",
  },
  "connection-google-aut": {
    src: "/img/curated/connection-google-aut-1920.webp",
    srcSet: {
      "1920": "/img/curated/connection-google-aut-1920.webp",
      "1280": "/img/curated/connection-google-aut-1280.webp",
      "768": "/img/curated/connection-google-aut-768.webp",
    },
    width: 1920,
    height: 1280,
    role: "card",
    alt: "Three She Sharp volunteers in branded T-shirts standing arm in arm and smiling together at a Google event.",
  },
  "connection-ai-hackathon": {
    src: "/img/curated/connection-ai-hackathon-1920.webp",
    srcSet: {
      "1920": "/img/curated/connection-ai-hackathon-1920.webp",
      "1280": "/img/curated/connection-ai-hackathon-1280.webp",
      "768": "/img/curated/connection-ai-hackathon-768.webp",
    },
    width: 1920,
    height: 1440,
    role: "card",
    alt: "Four smiling women posed closely together at the She Sharp AI for the Environment hackathon.",
  },
} as const satisfies Record<string, CuratedImage>;

export type CuratedImageKey = keyof typeof curatedImages;

/** Build a `srcSet` attribute string (width descriptors) from a curated entry. */
export function toSrcSet(img: CuratedImage): string {
  return Object.entries(img.srcSet)
    .map(([w, url]) => `${url} ${w}w`)
    .join(", ");
}
