// AUTO-GENERATED by scripts/events/build-event-poster.ts — do not edit by hand.
//
// Promotional graphics for this event that no page on the website renders:
// the speaker and line-up tiles, posted to LinkedIn and Instagram one at a
// time over the weeks before the event, and the mailing-list banner, which an
// email links by absolute URL. Naming them here rather than in
// scripts/verify-image-paths.ts means the forward check guards them too —
// delete one and CI fails, instead of CI staying green while a scheduled post
// loses its picture or an announcement goes out with a hole in it.
//
// NEVER point coverImage.url at one of these. A speaker poster has no safe
// band, so an event card would crop the person's name away, and the email
// banner is 2:1 — the website's cover is the 4:5 social WebP, which carries
// the band every card crop was checked against.

export interface PromoGraphic {
  file: string;
  subject: string;
  alt: string;
}

export const promoGraphics: PromoGraphic[] = [
  {
    file: "/img/events/code-secure-2026/email.jpg",
    subject: "Code Secure. Lead the Future: Women in Cybersecurity",
    alt: "Code Secure. Lead the Future: Women in Cybersecurity — the banner She Sharp's mailing-list announcement opens with.",
  },
  {
    file: "/img/events/code-secure-2026/humanitix.jpg",
    subject: "Meet the Speaker",
    alt: "Meet the Speaker: every speaker at Code Secure. Lead the Future: Women in Cybersecurity, on one She Sharp promotional graphic.",
  },
  {
    file: "/img/events/code-secure-2026/social.jpg",
    subject: "Meet the Speaker",
    alt: "Meet the Speaker: every speaker at Code Secure. Lead the Future: Women in Cybersecurity, on one She Sharp promotional graphic.",
  },
  {
    file: "/img/events/code-secure-2026/square.jpg",
    subject: "Meet the Speaker",
    alt: "Meet the Speaker: every speaker at Code Secure. Lead the Future: Women in Cybersecurity, on one She Sharp promotional graphic.",
  },
  {
    file: "/img/events/code-secure-2026/square.webp",
    subject: "Meet the Speaker",
    alt: "Meet the Speaker: every speaker at Code Secure. Lead the Future: Women in Cybersecurity, on one She Sharp promotional graphic.",
  },
  {
    file: "/img/events/code-secure-2026/story.jpg",
    subject: "Meet the Speaker",
    alt: "Meet the Speaker: every speaker at Code Secure. Lead the Future: Women in Cybersecurity, on one She Sharp promotional graphic.",
  },
  {
    file: "/img/events/code-secure-2026/story.webp",
    subject: "Meet the Speaker",
    alt: "Meet the Speaker: every speaker at Code Secure. Lead the Future: Women in Cybersecurity, on one She Sharp promotional graphic.",
  },
];
