// AUTO-GENERATED by scripts/events/build-event-poster.ts — do not edit by hand.
//
// Promotional graphics for this event that no page on the website renders:
// the speaker and line-up tiles, posted to LinkedIn and Instagram one at a
// time over the weeks before the event, and the mailing-list banner, which an
// email links by absolute URL. Naming them here rather than in
// scripts/verify-image-paths.ts means the forward check guards them too —
// delete one and CI fails, instead of CI staying green while a scheduled post
// loses its picture or an announcement goes out with a hole in it.
//
// NEVER point coverImage.url at one of these. A speaker poster has no safe
// band, so an event card would crop the person's name away, and the email
// banner is 2:1 — the website's cover is the 4:5 social WebP, which carries
// the band every card crop was checked against.

export interface PromoGraphic {
  file: string;
  subject: string;
  alt: string;
}

export const promoGraphics: PromoGraphic[] = [
  {
    file: "/img/events/she-sharp-and-myob-working-smarter/email.jpg",
    subject: "Working Smarter: AI, MYOB, and the New Delivery Landscape",
    alt: "Working Smarter: AI, MYOB, and the New Delivery Landscape — the banner She Sharp's mailing-list announcement opens with.",
  },
  {
    file: "/img/events/she-sharp-and-myob-working-smarter/humanitix.jpg",
    subject: "Meet Our Speakers",
    alt: "Meet Our Speakers: every speaker at Working Smarter: AI, MYOB, and the New Delivery Landscape, on one She Sharp promotional graphic.",
  },
  {
    file: "/img/events/she-sharp-and-myob-working-smarter/lineup-social.jpg",
    subject: "Meet Our Speakers",
    alt: "Meet Our Speakers: every speaker at Working Smarter: AI, MYOB, and the New Delivery Landscape, on one She Sharp promotional graphic.",
  },
  {
    file: "/img/events/she-sharp-and-myob-working-smarter/social.jpg",
    subject: "Meet Our Speakers",
    alt: "Meet Our Speakers: every speaker at Working Smarter: AI, MYOB, and the New Delivery Landscape, on one She Sharp promotional graphic.",
  },
  {
    file: "/img/events/she-sharp-and-myob-working-smarter/speaker-jean-fulop-social.jpg",
    subject: "Jean Fulop",
    alt: "Jean Fulop — a She Sharp promotional graphic for Working Smarter: AI, MYOB, and the New Delivery Landscape.",
  },
  {
    file: "/img/events/she-sharp-and-myob-working-smarter/speaker-jean-fulop-square.jpg",
    subject: "Jean Fulop",
    alt: "Jean Fulop — a She Sharp promotional graphic for Working Smarter: AI, MYOB, and the New Delivery Landscape.",
  },
  {
    file: "/img/events/she-sharp-and-myob-working-smarter/speaker-jean-fulop-story.jpg",
    subject: "Jean Fulop",
    alt: "Jean Fulop — a She Sharp promotional graphic for Working Smarter: AI, MYOB, and the New Delivery Landscape.",
  },
  {
    file: "/img/events/she-sharp-and-myob-working-smarter/speaker-katy-seel-social.jpg",
    subject: "Katy Seel",
    alt: "Katy Seel — a She Sharp promotional graphic for Working Smarter: AI, MYOB, and the New Delivery Landscape.",
  },
  {
    file: "/img/events/she-sharp-and-myob-working-smarter/speaker-katy-seel-square.jpg",
    subject: "Katy Seel",
    alt: "Katy Seel — a She Sharp promotional graphic for Working Smarter: AI, MYOB, and the New Delivery Landscape.",
  },
  {
    file: "/img/events/she-sharp-and-myob-working-smarter/speaker-katy-seel-story.jpg",
    subject: "Katy Seel",
    alt: "Katy Seel — a She Sharp promotional graphic for Working Smarter: AI, MYOB, and the New Delivery Landscape.",
  },
  {
    file: "/img/events/she-sharp-and-myob-working-smarter/speaker-marion-nicholas-social.jpg",
    subject: "Marion Nicholas",
    alt: "Marion Nicholas — a She Sharp promotional graphic for Working Smarter: AI, MYOB, and the New Delivery Landscape.",
  },
  {
    file: "/img/events/she-sharp-and-myob-working-smarter/speaker-marion-nicholas-square.jpg",
    subject: "Marion Nicholas",
    alt: "Marion Nicholas — a She Sharp promotional graphic for Working Smarter: AI, MYOB, and the New Delivery Landscape.",
  },
  {
    file: "/img/events/she-sharp-and-myob-working-smarter/speaker-marion-nicholas-story.jpg",
    subject: "Marion Nicholas",
    alt: "Marion Nicholas — a She Sharp promotional graphic for Working Smarter: AI, MYOB, and the New Delivery Landscape.",
  },
  {
    file: "/img/events/she-sharp-and-myob-working-smarter/square.jpg",
    subject: "Meet Our Speakers",
    alt: "Meet Our Speakers: every speaker at Working Smarter: AI, MYOB, and the New Delivery Landscape, on one She Sharp promotional graphic.",
  },
  {
    file: "/img/events/she-sharp-and-myob-working-smarter/square.webp",
    subject: "Meet Our Speakers",
    alt: "Meet Our Speakers: every speaker at Working Smarter: AI, MYOB, and the New Delivery Landscape, on one She Sharp promotional graphic.",
  },
  {
    file: "/img/events/she-sharp-and-myob-working-smarter/story.jpg",
    subject: "Meet Our Speakers",
    alt: "Meet Our Speakers: every speaker at Working Smarter: AI, MYOB, and the New Delivery Landscape, on one She Sharp promotional graphic.",
  },
  {
    file: "/img/events/she-sharp-and-myob-working-smarter/story.webp",
    subject: "Meet Our Speakers",
    alt: "Meet Our Speakers: every speaker at Working Smarter: AI, MYOB, and the New Delivery Landscape, on one She Sharp promotional graphic.",
  },
];
