/**
 * AUTO-GENERATED by scripts/build-event-archive.mts — do not edit by hand.
 *
 * Archive photos for past events that ship no on-page photo set of their own.
 * Keyed by event slug. Consumed by the event detail page (photo gallery) and
 * the resources photo-gallery mosaics.
 *
 * Regenerate a single event with:
 *   npx tsx scripts/build-event-archive.mts --slug <slug>
 */

export interface EventArchivePhoto {
  src: string;
  width: number;
  height: number;
  alt: string;
}

export const eventArchivePhotos: Record<string, EventArchivePhoto[]> = {
  "her-waka-june-2026": [
    { src: "/img/events/archive/her-waka-june-2026/1.webp", width: 1280, height: 853, alt: "Her Waka (June 2026) — Personal Branding & Growth Tips — She Sharp event photo 1" },
    { src: "/img/events/archive/her-waka-june-2026/2.webp", width: 1280, height: 853, alt: "Her Waka (June 2026) — Personal Branding & Growth Tips — She Sharp event photo 2" },
    { src: "/img/events/archive/her-waka-june-2026/3.webp", width: 1280, height: 853, alt: "Her Waka (June 2026) — Personal Branding & Growth Tips — She Sharp event photo 3" },
    { src: "/img/events/archive/her-waka-june-2026/4.webp", width: 1280, height: 853, alt: "Her Waka (June 2026) — Personal Branding & Growth Tips — She Sharp event photo 4" },
  ],
  "making-linkedin-work-for-you-with-stuart-little": [
    { src: "/img/events/archive/making-linkedin-work-for-you-with-stuart-little/1.webp", width: 1280, height: 853, alt: "Making Linkedin Work for You — She Sharp event photo 1" },
    { src: "/img/events/archive/making-linkedin-work-for-you-with-stuart-little/2.webp", width: 1280, height: 853, alt: "Making Linkedin Work for You — She Sharp event photo 2" },
    { src: "/img/events/archive/making-linkedin-work-for-you-with-stuart-little/3.webp", width: 1280, height: 853, alt: "Making Linkedin Work for You — She Sharp event photo 3" },
    { src: "/img/events/archive/making-linkedin-work-for-you-with-stuart-little/4.webp", width: 1280, height: 853, alt: "Making Linkedin Work for You — She Sharp event photo 4" },
  ],
  "she-sharp-and-academyex-international-womens-day-2026": [
    { src: "/img/events/archive/she-sharp-and-academyex-international-womens-day-2026/1.webp", width: 1280, height: 853, alt: "She Sharp & academyEX: International Women's Day 2026 — She Sharp event photo 1" },
    { src: "/img/events/archive/she-sharp-and-academyex-international-womens-day-2026/2.webp", width: 1280, height: 853, alt: "She Sharp & academyEX: International Women's Day 2026 — She Sharp event photo 2" },
    { src: "/img/events/archive/she-sharp-and-academyex-international-womens-day-2026/3.webp", width: 1280, height: 853, alt: "She Sharp & academyEX: International Women's Day 2026 — She Sharp event photo 3" },
    { src: "/img/events/archive/she-sharp-and-academyex-international-womens-day-2026/4.webp", width: 1280, height: 853, alt: "She Sharp & academyEX: International Women's Day 2026 — She Sharp event photo 4" },
  ],
  "she-sharp-candice-murray-own-your-energy": [
    { src: "/img/events/archive/she-sharp-candice-murray-own-your-energy/1.webp", width: 1280, height: 853, alt: "Own Your Energy with Candice Murray – Presented by She Sharp & Metlifecare — She Sharp event photo 1" },
    { src: "/img/events/archive/she-sharp-candice-murray-own-your-energy/2.webp", width: 1280, height: 853, alt: "Own Your Energy with Candice Murray – Presented by She Sharp & Metlifecare — She Sharp event photo 2" },
    { src: "/img/events/archive/she-sharp-candice-murray-own-your-energy/3.webp", width: 1280, height: 853, alt: "Own Your Energy with Candice Murray – Presented by She Sharp & Metlifecare — She Sharp event photo 3" },
    { src: "/img/events/archive/she-sharp-candice-murray-own-your-energy/4.webp", width: 1280, height: 853, alt: "Own Your Energy with Candice Murray – Presented by She Sharp & Metlifecare — She Sharp event photo 4" },
  ],
  "her-waka": [
    { src: "/img/events/archive/her-waka/1.webp", width: 1280, height: 853, alt: "HER WAKA — Navigating Pathways into Sustainable Employment — She Sharp event photo 1" },
    { src: "/img/events/archive/her-waka/2.webp", width: 1280, height: 853, alt: "HER WAKA — Navigating Pathways into Sustainable Employment — She Sharp event photo 2" },
    { src: "/img/events/archive/her-waka/3.webp", width: 1280, height: 853, alt: "HER WAKA — Navigating Pathways into Sustainable Employment — She Sharp event photo 3" },
    { src: "/img/events/archive/her-waka/4.webp", width: 1280, height: 853, alt: "HER WAKA — Navigating Pathways into Sustainable Employment — She Sharp event photo 4" },
  ],
  "her-waka-april-2026": [
    { src: "/img/events/archive/her-waka-april-2026/1.webp", width: 1280, height: 853, alt: "Her Waka (April 2026) — #IAmRemarkable & Vibe Coding — She Sharp event photo 1" },
    { src: "/img/events/archive/her-waka-april-2026/2.webp", width: 1280, height: 853, alt: "Her Waka (April 2026) — #IAmRemarkable & Vibe Coding — She Sharp event photo 2" },
    { src: "/img/events/archive/her-waka-april-2026/3.webp", width: 1280, height: 853, alt: "Her Waka (April 2026) — #IAmRemarkable & Vibe Coding — She Sharp event photo 3" },
    { src: "/img/events/archive/her-waka-april-2026/4.webp", width: 1280, height: 853, alt: "Her Waka (April 2026) — #IAmRemarkable & Vibe Coding — She Sharp event photo 4" },
  ],
  "her-waka-may-2026": [
    { src: "/img/events/archive/her-waka-may-2026/1.webp", width: 1280, height: 853, alt: "Her Waka (May 2026) — Cybersecurity Workshop — She Sharp event photo 1" },
    { src: "/img/events/archive/her-waka-may-2026/2.webp", width: 1280, height: 853, alt: "Her Waka (May 2026) — Cybersecurity Workshop — She Sharp event photo 2" },
    { src: "/img/events/archive/her-waka-may-2026/3.webp", width: 1280, height: 853, alt: "Her Waka (May 2026) — Cybersecurity Workshop — She Sharp event photo 3" },
    { src: "/img/events/archive/her-waka-may-2026/4.webp", width: 1280, height: 853, alt: "Her Waka (May 2026) — Cybersecurity Workshop — She Sharp event photo 4" },
  ],
  "code-secure": [
    { src: "/img/events/archive/code-secure/1.webp", width: 1280, height: 853, alt: "Code Secure. Lead the Future: Women in Cybersecurity Workshop — She Sharp event photo 1" },
    { src: "/img/events/archive/code-secure/2.webp", width: 1280, height: 853, alt: "Code Secure. Lead the Future: Women in Cybersecurity Workshop — She Sharp event photo 2" },
    { src: "/img/events/archive/code-secure/3.webp", width: 1280, height: 853, alt: "Code Secure. Lead the Future: Women in Cybersecurity Workshop — She Sharp event photo 3" },
    { src: "/img/events/archive/code-secure/4.webp", width: 1280, height: 853, alt: "Code Secure. Lead the Future: Women in Cybersecurity Workshop — She Sharp event photo 4" },
  ],
  "business-and-technology-transformation-through-platforms-and-products": [
    { src: "/img/events/archive/business-and-technology-transformation-through-platforms-and-products/1.webp", width: 1280, height: 853, alt: "Business and Technology Transformation Through Platforms and Products — She Sharp event photo 1" },
    { src: "/img/events/archive/business-and-technology-transformation-through-platforms-and-products/2.webp", width: 1280, height: 853, alt: "Business and Technology Transformation Through Platforms and Products — She Sharp event photo 2" },
    { src: "/img/events/archive/business-and-technology-transformation-through-platforms-and-products/3.webp", width: 1280, height: 853, alt: "Business and Technology Transformation Through Platforms and Products — She Sharp event photo 3" },
    { src: "/img/events/archive/business-and-technology-transformation-through-platforms-and-products/4.webp", width: 1280, height: 853, alt: "Business and Technology Transformation Through Platforms and Products — She Sharp event photo 4" },
  ],
  "thrive-your-career-your-story": [
    { src: "/img/events/archive/thrive-your-career-your-story/1.webp", width: 1280, height: 853, alt: "THRIVE: Your Career, Your Story — She Sharp event photo 1" },
    { src: "/img/events/archive/thrive-your-career-your-story/2.webp", width: 1280, height: 853, alt: "THRIVE: Your Career, Your Story — She Sharp event photo 2" },
    { src: "/img/events/archive/thrive-your-career-your-story/3.webp", width: 1280, height: 853, alt: "THRIVE: Your Career, Your Story — She Sharp event photo 3" },
    { src: "/img/events/archive/thrive-your-career-your-story/4.webp", width: 1280, height: 853, alt: "THRIVE: Your Career, Your Story — She Sharp event photo 4" },
  ],
  "ai-hackathon-festival-2025": [
    { src: "/img/events/archive/ai-hackathon-festival-2025/1.webp", width: 1280, height: 853, alt: "AI Hackathon Festival 2025 — She Sharp event photo 1" },
    { src: "/img/events/archive/ai-hackathon-festival-2025/2.webp", width: 1280, height: 853, alt: "AI Hackathon Festival 2025 — She Sharp event photo 2" },
    { src: "/img/events/archive/ai-hackathon-festival-2025/3.webp", width: 1280, height: 853, alt: "AI Hackathon Festival 2025 — She Sharp event photo 3" },
    { src: "/img/events/archive/ai-hackathon-festival-2025/4.webp", width: 1280, height: 853, alt: "AI Hackathon Festival 2025 — She Sharp event photo 4" },
  ],
  "iamremarkable": [
    { src: "/img/events/archive/iamremarkable/1.webp", width: 1280, height: 666, alt: "#IAmRemarkable — She Sharp event photo 1" },
    { src: "/img/events/archive/iamremarkable/2.webp", width: 1280, height: 666, alt: "#IAmRemarkable — She Sharp event photo 2" },
  ],
  "she-sharp-and-myob-working-smarter": [
    { src: "/img/events/archive/she-sharp-and-myob-working-smarter/1.webp", width: 1280, height: 854, alt: "Working Smarter: AI, MYOB, and the New Delivery Landscape — She Sharp event photo 1" },
    { src: "/img/events/archive/she-sharp-and-myob-working-smarter/2.webp", width: 1280, height: 854, alt: "Working Smarter: AI, MYOB, and the New Delivery Landscape — She Sharp event photo 2" },
    { src: "/img/events/archive/she-sharp-and-myob-working-smarter/3.webp", width: 1280, height: 854, alt: "Working Smarter: AI, MYOB, and the New Delivery Landscape — She Sharp event photo 3" },
    { src: "/img/events/archive/she-sharp-and-myob-working-smarter/4.webp", width: 1280, height: 854, alt: "Working Smarter: AI, MYOB, and the New Delivery Landscape — She Sharp event photo 4" },
    { src: "/img/events/archive/she-sharp-and-myob-working-smarter/5.webp", width: 1280, height: 854, alt: "Working Smarter: AI, MYOB, and the New Delivery Landscape — She Sharp event photo 5" },
  ],
  "she-storytellers-series-2-0": [
    { src: "/img/events/archive/she-storytellers-series-2-0/1.webp", width: 1000, height: 650, alt: "SHE# Storytellers Series 2.0 — She Sharp event photo 1" },
    { src: "/img/events/archive/she-storytellers-series-2-0/2.webp", width: 1000, height: 650, alt: "SHE# Storytellers Series 2.0 — She Sharp event photo 2" },
    { src: "/img/events/archive/she-storytellers-series-2-0/3.webp", width: 1000, height: 650, alt: "SHE# Storytellers Series 2.0 — She Sharp event photo 3" },
  ],
  "superhero-daughter-day": [
    { src: "/img/events/archive/superhero-daughter-day/1.webp", width: 1000, height: 650, alt: "SUPERHERO DAUGHTER DAY — She Sharp event photo 1" },
    { src: "/img/events/archive/superhero-daughter-day/2.webp", width: 1000, height: 650, alt: "SUPERHERO DAUGHTER DAY — She Sharp event photo 2" },
  ],
  "online-quiz-night-celebrating-ada-lovelace-day": [
    { src: "/img/events/archive/online-quiz-night-celebrating-ada-lovelace-day/1.webp", width: 1000, height: 650, alt: "Online Quiz Night celebrating Ada Lovelace Day — She Sharp event photo 1" },
    { src: "/img/events/archive/online-quiz-night-celebrating-ada-lovelace-day/2.webp", width: 1000, height: 650, alt: "Online Quiz Night celebrating Ada Lovelace Day — She Sharp event photo 2" },
    { src: "/img/events/archive/online-quiz-night-celebrating-ada-lovelace-day/3.webp", width: 1000, height: 650, alt: "Online Quiz Night celebrating Ada Lovelace Day — She Sharp event photo 3" },
  ],
};
