/**
 * AUTO-GENERATED by scripts/build-event-archive.mts — do not edit by hand.
 *
 * Archive photos for past events that ship no on-page photo set of their own.
 * Keyed by event slug. Consumed by the event detail page (photo gallery) and
 * the resources photo-gallery mosaics.
 *
 * Regenerate a single event with:
 *   npx tsx scripts/build-event-archive.mts --slug <slug>
 */

export interface EventArchivePhoto {
  src: string;
  width: number;
  height: number;
  alt: string;
}

export const eventArchivePhotos: Record<string, EventArchivePhoto[]> = {
  "her-waka-june-2026": [
    { src: "/img/events/her-waka-june-2026/archive/1.webp", width: 1280, height: 853, alt: "Her Waka (June 2026) — Personal Branding & Growth Tips — She Sharp event photo 1" },
    { src: "/img/events/her-waka-june-2026/archive/2.webp", width: 1280, height: 853, alt: "Her Waka (June 2026) — Personal Branding & Growth Tips — She Sharp event photo 2" },
    { src: "/img/events/her-waka-june-2026/archive/3.webp", width: 1280, height: 853, alt: "Her Waka (June 2026) — Personal Branding & Growth Tips — She Sharp event photo 3" },
    { src: "/img/events/her-waka-june-2026/archive/4.webp", width: 1280, height: 853, alt: "Her Waka (June 2026) — Personal Branding & Growth Tips — She Sharp event photo 4" },
  ],
  "making-linkedin-work-for-you-with-stuart-little": [
    { src: "/img/events/making-linkedin-work-for-you-with-stuart-little/archive/1.webp", width: 1280, height: 853, alt: "Making LinkedIn Work for You — She Sharp event photo 1" },
    { src: "/img/events/making-linkedin-work-for-you-with-stuart-little/archive/2.webp", width: 1280, height: 853, alt: "Making LinkedIn Work for You — She Sharp event photo 2" },
    { src: "/img/events/making-linkedin-work-for-you-with-stuart-little/archive/3.webp", width: 1280, height: 853, alt: "Making LinkedIn Work for You — She Sharp event photo 3" },
    { src: "/img/events/making-linkedin-work-for-you-with-stuart-little/archive/4.webp", width: 1280, height: 853, alt: "Making LinkedIn Work for You — She Sharp event photo 4" },
  ],
  "she-sharp-and-academyex-international-womens-day-2026": [
    { src: "/img/events/she-sharp-and-academyex-international-womens-day-2026/archive/1.webp", width: 1280, height: 853, alt: "She Sharp & academyEX: International Women's Day 2026 — She Sharp event photo 1" },
    { src: "/img/events/she-sharp-and-academyex-international-womens-day-2026/archive/2.webp", width: 1280, height: 853, alt: "She Sharp & academyEX: International Women's Day 2026 — She Sharp event photo 2" },
    { src: "/img/events/she-sharp-and-academyex-international-womens-day-2026/archive/3.webp", width: 1280, height: 853, alt: "She Sharp & academyEX: International Women's Day 2026 — She Sharp event photo 3" },
    { src: "/img/events/she-sharp-and-academyex-international-womens-day-2026/archive/4.webp", width: 1280, height: 853, alt: "She Sharp & academyEX: International Women's Day 2026 — She Sharp event photo 4" },
  ],
  "she-sharp-candice-murray-own-your-energy": [
    { src: "/img/events/she-sharp-candice-murray-own-your-energy/archive/1.webp", width: 1280, height: 853, alt: "Own Your Energy with Candice Murray – Presented by She Sharp & Metlifecare — She Sharp event photo 1" },
    { src: "/img/events/she-sharp-candice-murray-own-your-energy/archive/2.webp", width: 1280, height: 853, alt: "Own Your Energy with Candice Murray – Presented by She Sharp & Metlifecare — She Sharp event photo 2" },
    { src: "/img/events/she-sharp-candice-murray-own-your-energy/archive/3.webp", width: 1280, height: 853, alt: "Own Your Energy with Candice Murray – Presented by She Sharp & Metlifecare — She Sharp event photo 3" },
    { src: "/img/events/she-sharp-candice-murray-own-your-energy/archive/4.webp", width: 1280, height: 853, alt: "Own Your Energy with Candice Murray – Presented by She Sharp & Metlifecare — She Sharp event photo 4" },
  ],
  "her-waka": [
    { src: "/img/events/her-waka/archive/1.webp", width: 1280, height: 853, alt: "HER WAKA — Navigating Pathways into Sustainable Employment — She Sharp event photo 1" },
    { src: "/img/events/her-waka/archive/2.webp", width: 1280, height: 853, alt: "HER WAKA — Navigating Pathways into Sustainable Employment — She Sharp event photo 2" },
    { src: "/img/events/her-waka/archive/3.webp", width: 1280, height: 853, alt: "HER WAKA — Navigating Pathways into Sustainable Employment — She Sharp event photo 3" },
    { src: "/img/events/her-waka/archive/4.webp", width: 1280, height: 853, alt: "HER WAKA — Navigating Pathways into Sustainable Employment — She Sharp event photo 4" },
  ],
  "her-waka-april-2026": [
    { src: "/img/events/her-waka-april-2026/archive/1.webp", width: 1280, height: 853, alt: "Her Waka (April 2026) — #IAmRemarkable — She Sharp event photo 1" },
    { src: "/img/events/her-waka-april-2026/archive/2.webp", width: 1280, height: 853, alt: "Her Waka (April 2026) — #IAmRemarkable — She Sharp event photo 2" },
    { src: "/img/events/her-waka-april-2026/archive/3.webp", width: 1280, height: 853, alt: "Her Waka (April 2026) — #IAmRemarkable — She Sharp event photo 3" },
    { src: "/img/events/her-waka-april-2026/archive/4.webp", width: 1280, height: 853, alt: "Her Waka (April 2026) — #IAmRemarkable — She Sharp event photo 4" },
  ],
  "her-waka-may-2026": [
    { src: "/img/events/her-waka-may-2026/archive/1.webp", width: 1280, height: 853, alt: "Her Waka (May 2026) — Cybersecurity Workshop — She Sharp event photo 1" },
    { src: "/img/events/her-waka-may-2026/archive/2.webp", width: 1280, height: 853, alt: "Her Waka (May 2026) — Cybersecurity Workshop — She Sharp event photo 2" },
    { src: "/img/events/her-waka-may-2026/archive/3.webp", width: 1280, height: 853, alt: "Her Waka (May 2026) — Cybersecurity Workshop — She Sharp event photo 3" },
    { src: "/img/events/her-waka-may-2026/archive/4.webp", width: 1280, height: 853, alt: "Her Waka (May 2026) — Cybersecurity Workshop — She Sharp event photo 4" },
  ],
  "code-secure": [
    { src: "/img/events/code-secure/archive/1.webp", width: 1280, height: 853, alt: "Code Secure. Lead the Future: Women in Cybersecurity Workshop — She Sharp event photo 1" },
    { src: "/img/events/code-secure/archive/2.webp", width: 1280, height: 853, alt: "Code Secure. Lead the Future: Women in Cybersecurity Workshop — She Sharp event photo 2" },
    { src: "/img/events/code-secure/archive/3.webp", width: 1280, height: 853, alt: "Code Secure. Lead the Future: Women in Cybersecurity Workshop — She Sharp event photo 3" },
    { src: "/img/events/code-secure/archive/4.webp", width: 1280, height: 853, alt: "Code Secure. Lead the Future: Women in Cybersecurity Workshop — She Sharp event photo 4" },
  ],
  "business-and-technology-transformation-through-platforms-and-products": [
    { src: "/img/events/business-and-technology-transformation-through-platforms-and-products/archive/1.webp", width: 1280, height: 853, alt: "Business and Technology Transformation Through Platforms and Products — She Sharp event photo 1" },
    { src: "/img/events/business-and-technology-transformation-through-platforms-and-products/archive/2.webp", width: 1280, height: 853, alt: "Business and Technology Transformation Through Platforms and Products — She Sharp event photo 2" },
    { src: "/img/events/business-and-technology-transformation-through-platforms-and-products/archive/3.webp", width: 1280, height: 853, alt: "Business and Technology Transformation Through Platforms and Products — She Sharp event photo 3" },
    { src: "/img/events/business-and-technology-transformation-through-platforms-and-products/archive/4.webp", width: 1280, height: 853, alt: "Business and Technology Transformation Through Platforms and Products — She Sharp event photo 4" },
  ],
  "thrive-your-career-your-story": [
    { src: "/img/events/thrive-your-career-your-story/archive/1.webp", width: 1280, height: 853, alt: "THRIVE: Your Career, Your Story — She Sharp event photo 1" },
    { src: "/img/events/thrive-your-career-your-story/archive/2.webp", width: 1280, height: 853, alt: "THRIVE: Your Career, Your Story — She Sharp event photo 2" },
    { src: "/img/events/thrive-your-career-your-story/archive/3.webp", width: 1280, height: 853, alt: "THRIVE: Your Career, Your Story — She Sharp event photo 3" },
    { src: "/img/events/thrive-your-career-your-story/archive/4.webp", width: 1280, height: 853, alt: "THRIVE: Your Career, Your Story — She Sharp event photo 4" },
  ],
  "ai-hackathon-festival-2025": [
    { src: "/img/events/ai-hackathon-festival-2025/archive/1.webp", width: 1280, height: 853, alt: "AI Hackathon Festival 2025 — She Sharp event photo 1" },
    { src: "/img/events/ai-hackathon-festival-2025/archive/2.webp", width: 1280, height: 853, alt: "AI Hackathon Festival 2025 — She Sharp event photo 2" },
    { src: "/img/events/ai-hackathon-festival-2025/archive/3.webp", width: 1280, height: 853, alt: "AI Hackathon Festival 2025 — She Sharp event photo 3" },
    { src: "/img/events/ai-hackathon-festival-2025/archive/4.webp", width: 1280, height: 853, alt: "AI Hackathon Festival 2025 — She Sharp event photo 4" },
  ],
  "iamremarkable": [
    { src: "/img/events/iamremarkable/archive/1.webp", width: 1280, height: 666, alt: "#IAmRemarkable — She Sharp event photo 1" },
    { src: "/img/events/iamremarkable/archive/2.webp", width: 1280, height: 666, alt: "#IAmRemarkable — She Sharp event photo 2" },
  ],
  "she-sharp-and-myob-working-smarter": [
    { src: "/img/events/she-sharp-and-myob-working-smarter/archive/1.webp", width: 1280, height: 854, alt: "Working Smarter: AI, MYOB, and the New Delivery Landscape — She Sharp event photo 1" },
    { src: "/img/events/she-sharp-and-myob-working-smarter/archive/2.webp", width: 1280, height: 854, alt: "Working Smarter: AI, MYOB, and the New Delivery Landscape — She Sharp event photo 2" },
    { src: "/img/events/she-sharp-and-myob-working-smarter/archive/3.webp", width: 1280, height: 854, alt: "Working Smarter: AI, MYOB, and the New Delivery Landscape — She Sharp event photo 3" },
    { src: "/img/events/she-sharp-and-myob-working-smarter/archive/4.webp", width: 1280, height: 854, alt: "Working Smarter: AI, MYOB, and the New Delivery Landscape — She Sharp event photo 4" },
    { src: "/img/events/she-sharp-and-myob-working-smarter/archive/5.webp", width: 1280, height: 854, alt: "Working Smarter: AI, MYOB, and the New Delivery Landscape — She Sharp event photo 5" },
  ],
  "she-storytellers-series-2-0": [
    { src: "/img/events/she-storytellers-series-2-0/archive/1.webp", width: 1000, height: 650, alt: "SHE# Storytellers Series 2.0 — She Sharp event photo 1" },
    { src: "/img/events/she-storytellers-series-2-0/archive/2.webp", width: 1000, height: 650, alt: "SHE# Storytellers Series 2.0 — She Sharp event photo 2" },
    { src: "/img/events/she-storytellers-series-2-0/archive/3.webp", width: 1000, height: 650, alt: "SHE# Storytellers Series 2.0 — She Sharp event photo 3" },
  ],
  "superhero-daughter-day": [
    { src: "/img/events/superhero-daughter-day/archive/1.webp", width: 1000, height: 650, alt: "SUPERHERO DAUGHTER DAY — She Sharp event photo 1" },
    { src: "/img/events/superhero-daughter-day/archive/2.webp", width: 1000, height: 650, alt: "SUPERHERO DAUGHTER DAY — She Sharp event photo 2" },
  ],
  "online-quiz-night-celebrating-ada-lovelace-day": [
    { src: "/img/events/online-quiz-night-celebrating-ada-lovelace-day/archive/1.webp", width: 1000, height: 650, alt: "Online Quiz Night celebrating Ada Lovelace Day — She Sharp event photo 1" },
    { src: "/img/events/online-quiz-night-celebrating-ada-lovelace-day/archive/2.webp", width: 1000, height: 650, alt: "Online Quiz Night celebrating Ada Lovelace Day — She Sharp event photo 2" },
    { src: "/img/events/online-quiz-night-celebrating-ada-lovelace-day/archive/3.webp", width: 1000, height: 650, alt: "Online Quiz Night celebrating Ada Lovelace Day — She Sharp event photo 3" },
  ],
};
