/**
 * build-email-playbook.mts — renders the email handbook into a page module.
 *
 * `/internal/email-playbook` is the sibling of `/internal/event-playbook`: the
 * same audience (a non-technical teammate who has never opened the repository),
 * the same treatment (one purpose-written document, compiled at authoring time
 * into a string the page renders), and a different subject. Email is not
 * event-scoped — the newsletter, marketing and events teams all send it, and
 * the rules are the same for all three — so it gets its own URL rather than a
 * ninth section inside a page whose navigation is one diagram of one evening.
 *
 * Usage:
 *   npx tsx scripts/docs/build-email-playbook.mts
 *   npx tsx scripts/docs/build-email-playbook.mts --check   (exit 1 if stale)
 *
 * **The renderer is imported, not forked.** `renderPlaybook()` in
 * `build-playbook.mts` already handles every subtlety this page needs — mermaid
 * fences reaching the browser as diagram source, prompt blocks wrapped so the
 * copy button has something to attach to, namespaced heading ids, scrollable
 * tables, and the CRLF collapse that keeps a Windows checkout and a Linux CI
 * runner hashing the same bytes. A second copy of that renderer would drift
 * from the first, and the drift would be invisible: both pages would still
 * render. Only the module preamble differs, and that is the whole of this file.
 *
 * `lib/docs/email-playbook.test.ts` is the gate that notices when the markdown
 * has moved on and this file has not been re-run.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// `.mjs`, not `.mts` and not extensionless. TypeScript rejects a `.mts`
// specifier without `allowImportingTsExtensions`, and neither Node's ESM
// resolver nor tsx will guess a `.mts` file from a bare name — the sibling
// scripts that import extensionlessly all point at `.ts` files, which tsx does
// resolve. `.mjs` is the form both halves accept: TypeScript maps it back to
// `.mts` and tsx loads the real file.
import { renderPlaybook } from "./build-playbook.mjs";

const REPO_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
);

/**
 * The one document, and its heading-id namespace.
 *
 * `email` rather than `playbook`, so that an anchor from one handbook pasted
 * into the other lands nowhere instead of landing on the wrong section — a dead
 * link is visible, a link to the wrong page is not.
 *
 * The filename avoids the `EMAIL_*.md` prefix that the engineering references
 * use (`EMAIL_OPERATIONS.md`, `EMAIL_PLATFORM_STATE.md`, …). Those are written
 * for whoever maintains the code; this one is written for whoever sends the
 * mail, and the `INTERNAL_` prefix is what says so at a glance in a directory
 * listing.
 */
const SOURCE = {
  key: "email",
  label: "Email Playbook",
  path: "docs/development/INTERNAL_EMAIL_PLAYBOOK.md",
} as const;

const TARGET = path.join(REPO_ROOT, "lib", "docs", "email-playbook.ts");

/** The command that fixes every failure this script or its test can report. */
const REBUILD_COMMAND = "npx tsx scripts/docs/build-email-playbook.mts";

/** Collapses CRLF, so `--check` fails on a change and never on a platform. */
function toLf(text: string): string {
  return text.replace(/\r\n/g, "\n");
}

/** The whole of the generated module, for the document as it stands on disk. */
export function renderModule(markdown: string): string {
  const [rendered] = renderPlaybook([{ spec: SOURCE, markdown }]);

  const manifest = [
    {
      key: rendered.key,
      label: rendered.label,
      path: rendered.path,
      sha256: rendered.sha256,
    },
  ];

  return `/**
 * The email handbook, rendered to HTML for \`/internal/email-playbook\`.
 *
 * AUTO-GENERATED by scripts/docs/build-email-playbook.mts — do not edit by hand.
 * Edit the markdown named in \`EMAIL_PLAYBOOK_SOURCES\` and re-run
 * \`${REBUILD_COMMAND}\`.
 *
 * The entry carries the sha256 of its markdown with LF line endings;
 * \`lib/docs/email-playbook.test.ts\` recomputes it and fails when it disagrees,
 * so a rewritten document can never sit behind a stale page.
 */

import type { PlaybookSource } from "./playbook";

export const EMAIL_PLAYBOOK_SOURCES: PlaybookSource[] = ${JSON.stringify(manifest, null, 2)};

// No contents structure, for the same reason the event playbook has none: the
// page is short numbered sections and a diagram, and a list of links above the
// diagram costs the top of the first screen to answer a question the reader
// does not have yet. Heading ids are still emitted, so a link to one section
// pasted into Slack still works.

// Embedded with JSON.stringify rather than a template literal: the document
// contains backticks and \`\${\`, both of which a template literal would either
// break on or interpolate.
export const EMAIL_PLAYBOOK_HTML = ${JSON.stringify(rendered.html)};
`;
}

function main(): void {
  const absolute = path.join(REPO_ROOT, SOURCE.path);
  if (!existsSync(absolute)) {
    console.error(`Missing source: ${SOURCE.path}`);
    process.exit(1);
  }

  const markdown = readFileSync(absolute, "utf8");
  const next = renderModule(markdown);
  const current = existsSync(TARGET) ? readFileSync(TARGET, "utf8") : "";

  const [rendered] = renderPlaybook([{ spec: SOURCE, markdown }]);
  const diagrams = (rendered.html.match(/<div class="mermaid">/g) ?? []).length;
  const prompts = (rendered.html.match(/<div class="playbook-prompt">/g) ?? [])
    .length;

  if (process.argv.includes("--check")) {
    if (toLf(current) === toLf(next)) {
      console.log(
        `lib/docs/email-playbook.ts is up to date ` +
          `(${diagrams} diagram(s), ${prompts} prompt block(s)).`,
      );
      return;
    }
    console.error(
      `lib/docs/email-playbook.ts is out of date with ${SOURCE.path}. ` +
        `Run: ${REBUILD_COMMAND}`,
    );
    process.exit(1);
  }

  if (toLf(current) === toLf(next)) {
    console.log(
      `lib/docs/email-playbook.ts already matched its source ` +
        `(${diagrams} diagram(s), ${prompts} prompt block(s)).`,
    );
    return;
  }

  writeFileSync(TARGET, next, "utf8");
  console.log(
    `Wrote lib/docs/email-playbook.ts — ${diagrams} diagram(s), ` +
      `${prompts} prompt block(s), ${next.length.toLocaleString()} bytes.`,
  );
  console.log(`  ${SOURCE.label}: ${SOURCE.path}`);
}

// Guarded the same way as its sibling. "build-email-playbook" does not contain
// "build-playbook", so importing the renderer above never runs that script's
// own `main()` — and running this one never runs it either.
if (process.argv[1]?.includes("build-email-playbook")) {
  main();
}
