/**
 * Scaffolds a new event deck from an event already in the repo.
 *
 * Usage:
 *   npx tsx scripts/deck/new-deck.ts <event-slug>
 *   npx tsx scripts/deck/new-deck.ts <event-slug> --force
 *
 * Writes `lib/deck/decks/<slug>.ts` with the opening and closing sequences
 * already wired up and the title, date, venue and partner logos filled in from
 * `lib/data/json/events-custom.json`. The event-specific middle is left as
 * clearly marked TODO blocks — that part is a judgement call about what the
 * room needs to see, and generating a guess would only be edited back out.
 *
 * Refuses to overwrite an existing deck unless `--force` is passed: a deck is
 * hand-written content, and losing an afternoon of copy to a re-run is not a
 * recoverable mistake.
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { getEventBySlug } from "@/lib/data/events";
import { COPY_LIMITS } from "@/lib/deck/lint";
import type { EventV3 } from "@/types/event";

const DECKS_DIR = join(process.cwd(), "lib", "deck", "decks");

/** Turns a slug into the camelCase export name the registry imports. */
function exportName(slug: string): string {
  const camel = slug
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part, index) =>
      index === 0
        ? part.charAt(0).toLowerCase() + part.slice(1)
        : part.charAt(0).toUpperCase() + part.slice(1),
    )
    .join("");
  return `${camel}Deck`;
}

/** Trims to at most `max` words, dropping any dangling punctuation. */
function truncateWords(text: string, max: number): string {
  const parts = text.trim().split(/\s+/).filter(Boolean);
  if (parts.length <= max) return text.trim();
  return parts.slice(0, max).join(" ").replace(/[,;:—–-]+$/, "");
}

/**
 * A title short enough to be a slide headline.
 *
 * Event titles carry the host and the partners ("… — AUT City Campus, hosted
 * with …"); a slide headline carries the event. Cuts at the first dash, then
 * clamps to the title-word limit.
 */
function slideTitle(event: EventV3): { title: string; wasCut: boolean } {
  const head = event.title.split(/\s+[—–-]\s+/)[0].split(",")[0].trim();
  const title = truncateWords(head, COPY_LIMITS.titleWords);
  return { title, wasCut: title !== event.title.trim() };
}

/** Up to three facts for under the headline: the date, the venue, the city. */
function titleMeta(event: EventV3): string[] {
  const location = event.detailPageData.location;
  return [
    event.detailPageData.time || event.date,
    location?.venueName,
    location?.city,
  ]
    .filter((value): value is string => !!value && value.trim().length > 0)
    .slice(0, COPY_LIMITS.titleMetaMax);
}

/** Renders a value as a TypeScript source literal. */
function literal(value: unknown): string {
  return JSON.stringify(value);
}

function template(event: EventV3): string {
  const slug = event.slug;
  const { title, wasCut } = slideTitle(event);
  const meta = titleMeta(event);
  const partners = event.detailPageData.sponsors?.main ?? [];
  const sectionCount = event.detailPageData.specialSections?.length ?? 0;

  const partnerLines = partners
    .map(
      (sponsor) =>
        `  { name: ${literal(sponsor.name)}, logo: ${literal(sponsor.logo)} },`,
    )
    .join("\n");

  return `/**
 * Deck: ${event.title}
 *
 * Generated by \`scripts/deck/new-deck.ts\`. Facts come from
 * \`lib/data/json/events-custom.json\` (${sectionCount} specialSections available).
 *
 * Next steps, in order:
 *   1. Fill in the karakia below — ask the host, do not guess the text.
 *   2. Replace the TODO block with this event's own slides.
 *   3. Register the deck in \`lib/deck/registry.ts\`.
 *   4. Run \`npx tsx scripts/deck/lint-deck.ts ${slug}\`.
 *
 * Long-form material — biographies, rules, terms, full venue lists — belongs on
 * the event page, which the "Stay Connected" QR reaches in one scan. Keep it
 * off the projector.
 */

import {
  buildClosingSlides,
  buildOpeningSlides,
  type KarakiaText,
} from "../boilerplate";
import type { Deck, DeckLogo, QrBlock } from "../types";

const EVENT_SLUG = ${literal(slug)};

// TODO: the karakia the host will read. Both arrays are required, one entry per
// spoken line, and the English is the translation of the te reo above it.
const OPENING_KARAKIA: KarakiaText = {
  teReo: ["TODO: opening karakia, line one"],
  english: ["TODO: English translation, line one"],
};

const CLOSING_KARAKIA: KarakiaText = {
  teReo: ["TODO: closing karakia, line one"],
  english: ["TODO: English translation, line one"],
};

/** Placeholder card until the printed QR codes are generated. */
const QR_PLACEHOLDER = "/img/decks/qr-placeholder.svg";

const WEBSITE_QR: QrBlock = {
  image: QR_PLACEHOLDER,
  url: "https://www.shesharp.org.nz",
  label: "She Sharp website",
  caption: "shesharp.org.nz",
};

const EVENTS_QR: QrBlock = {
  image: QR_PLACEHOLDER,
  url: "https://www.shesharp.org.nz/events",
  label: "Upcoming events",
  caption: "shesharp.org.nz/events",
};

const FEEDBACK_QR: QrBlock = {
  image: QR_PLACEHOLDER,
  // TODO: the real feedback form link.
  url: "https://www.shesharp.org.nz/events/" + EVENT_SLUG,
  label: "Feedback form",
  caption: "shesharp.org.nz/events",
};

const AMBASSADOR_QR: QrBlock = {
  image: QR_PLACEHOLDER,
  url: "https://www.shesharp.org.nz/join-our-team",
  label: "Become an ambassador",
  caption: "shesharp.org.nz/join-our-team",
};

/** Pre-filled from the event's \`sponsors.main\`. */
const PARTNER_LOGOS: DeckLogo[] = [
${partnerLines || "  // TODO: this event has no sponsors.main in the event JSON."}
];

export const ${exportName(slug)}: Deck = {
  slug: EVENT_SLUG,
  title: ${literal(title)},${wasCut ? `\n  // Shortened from: ${event.title}` : ""}
  eventSlug: EVENT_SLUG,
  // TODO: take the accent from the event poster. \`onDark\` must be lighter than
  // \`onLight\` — the brand purple scores 2.92:1 on the dark canvas and is
  // unreadable there. \`accentFromBrandColour()\` in ../theme fixes luminance.
  theme: {
    accent: {
      onLight: "#9b2e83",
      onDark: "#c846ab",
      spark: "#5ee7f5",
    },
  },
  slides: [
    ...buildOpeningSlides({
      eventTitle: ${literal(title)},
      eventMeta: ${literal(meta)},
      partnerLogos: PARTNER_LOGOS,
      karakia: OPENING_KARAKIA,
      // TODO: venue-specific safety lines, e.g. where the assembly point is.
      safetyExtras: [],
      contactQrs: [WEBSITE_QR, EVENTS_QR],
    }),

    // ---------------------------------------------------------------------
    // TODO: this event's own slides go here.
    //
    // Available slide types: agenda, bullets, break, contact, criteria, logos,
    // people, photo, photo-grid, prizes, qr-cta, section, stats, themes.
    //
    // Run sheets: parseTimedLines() in ../utils turns the event JSON's
    // "5:30–5:40pm — Event opening" lines straight into agenda rows.
    //
    // Every slide needs a unique kebab-case \`id\`, a \`section\` label, and a
    // \`note\` telling the host what to say. Copy limits are enforced.
    // ---------------------------------------------------------------------
    {
      id: "todo-first-slide",
      type: "section",
      section: "TODO: section name",
      index: "02",
      tone: "dark",
      title: "TODO: first chapter",
      note: "TODO: what the host says here.",
    },

    ...buildClosingSlides({
      thanksLogos: [{ label: "Hosts and sponsors", logos: PARTNER_LOGOS }],
      // TODO: mentors, judges and volunteers to thank by name.
      thanksNames: [],
      // TODO: snapshot from getUpcomingEvents() at authoring time — never call
      // it at render time, it is relative to today and would change the
      // projector content under the host.
      upcoming: [],
      feedbackQr: FEEDBACK_QR,
      ambassadorQr: AMBASSADOR_QR,
      karakia: CLOSING_KARAKIA,
    }),
  ],
};
`;
}

function main(): void {
  const args = process.argv.slice(2);
  const force = args.includes("--force");
  const slug = args.find((arg) => !arg.startsWith("--"));

  if (!slug) {
    console.error("Usage: npx tsx scripts/deck/new-deck.ts <event-slug> [--force]");
    process.exit(1);
  }

  const event = getEventBySlug(slug);
  if (!event) {
    console.error(`No event with slug "${slug}" in lib/data/json/events-custom.json.`);
    console.error(
      "Add the event first — the `sync-event-from-slack` skill puts it there.",
    );
    process.exit(1);
  }

  const target = join(DECKS_DIR, `${slug}.ts`);
  if (existsSync(target) && !force) {
    console.error(`${target} already exists.`);
    console.error("Pass --force to overwrite it, but read it first — deck copy is hand-written.");
    process.exit(1);
  }

  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, template(event), "utf8");

  console.log(`Wrote lib/deck/decks/${slug}.ts`);
  console.log("");
  console.log("Next:");
  console.log(`  1. Register it — add to lib/deck/registry.ts:`);
  console.log(`       import { ${exportName(slug)} } from "./decks/${slug}";`);
  console.log(`       [${exportName(slug)}.slug]: ${exportName(slug)},`);
  console.log(`  2. Check it — npx tsx scripts/deck/lint-deck.ts ${slug}`);
}

main();
