/**
 * Computes the Humanitix figures the H1 2026 funder report is waiting on, and
 * writes them out as paste-ready Typst.
 *
 * `report/data/report-data.typ` currently carries `registered: e(408)`,
 * `checked-in: e(297)`, `companies: p(96)` and two dozen per-event placeholders,
 * each with a note saying "Replace with the Humanitix export before FINAL" —
 * and `report/build.ps1 -Final` refuses to build while any of them is
 * unverified. This produces the replacements.
 *
 * It PRINTS rather than edits. `report-data.typ` is the report's single swap
 * surface and every `v()` note is an editorial claim somebody signs; a script
 * that rewrote it would be asserting provenance on a person's behalf. The
 * output goes to `tmp/humanitix/` for a human to read and paste.
 *
 * Two figures it deliberately refuses to produce: the two Youth Tech sessions
 * ran no check-in, so their `checked-in` has no value — not 0 — and the script
 * emits a comment saying so rather than a number that would read as "nobody
 * came to a workshop that demonstrably happened".
 *
 * Usage:
 *   npx tsx scripts/humanitix/report-metrics.ts
 *   npx tsx scripts/humanitix/report-metrics.ts --from 2026-01-01 --to 2026-06-30
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import {
  canonicalOrganisationId,
  getHumanitixInstances,
  humanitixCrosswalk,
  humanitixInstanceKey,
  humanitixManifest,
  normalizeHumanitixText,
} from "../../lib/data/humanitix";
import { parseDmyToIso, readCsv } from "./csv";
import { REPO_ROOT, argValue, vaultExists } from "./vault";

/**
 * The returning-attendee count and the per-event employer lists need per-person
 * and per-employer rows, which the committed archive deliberately does not
 * carry. So this script needs the vault — which is correct: a funder-report
 * figure should be computed from the source, once, by somebody who has it.
 */
function requireVault(exportId: string) {
  if (!vaultExists(exportId)) {
    console.error(
      `This script needs the raw export. Vault not found for ${exportId}.\n` +
        `  Set HUMANITIX_VAULT_DIR or place the CSVs in private/humanitix/${exportId}/.\n` +
        `  The committed archive holds aggregates only; the returning-attendee count\n` +
        `  and the employer lists come from the attendee rows and are never stored.`
    );
    process.exit(1);
  }
}

function main() {
  const argv = process.argv.slice(2);
  const from = argValue(argv, "--from") ?? "2026-01-01";
  const to = argValue(argv, "--to") ?? "2026-06-30";
  const exportId =
    argValue(argv, "--export") ?? humanitixManifest.exports.at(-1)?.exportId ?? "";

  requireVault(exportId);

  const spineFile = humanitixManifest.exports
    .find((entry) => entry.exportId === exportId)
    ?.files.find((file) => file.role === "spine");
  if (!spineFile) throw new Error(`No spine file recorded for export ${exportId}`);

  const spine = readCsv(exportId, spineFile.file);

  // First appearance per person, across the WHOLE archive — "returning" means
  // returning to She Sharp, not returning within the reporting window.
  const firstSeen = new Map<string, string>();
  for (const row of spine) {
    const email = (row["Email"] || row["Buyer email"] || "").trim().toLowerCase();
    if (!email) continue;
    const date = parseDmyToIso(row["Event date"] ?? "");
    const seen = firstSeen.get(email);
    if (!seen || date < seen) firstSeen.set(email, date);
  }

  const rowsByInstance = new Map<string, typeof spine>();
  for (const row of spine) {
    const key = humanitixInstanceKey(
      normalizeHumanitixText(row["Event"] ?? ""),
      parseDmyToIso(row["Event date"] ?? "")
    );
    rowsByInstance.set(key, [...(rowsByInstance.get(key) ?? []), row]);
  }

  const slugFor = (key: string) =>
    humanitixCrosswalk.links.find((link) => link.humanitixKey === key)?.siteSlug ??
    humanitixCrosswalk.series.find((series) => series.sessionKeys.includes(key))
      ?.siteSlug ??
    null;

  const window = getHumanitixInstances().filter(
    (instance) => instance.eventDate >= from && instance.eventDate <= to
  );

  const lines: string[] = [];
  const say = (text = "") => lines.push(text);

  say(`// Humanitix figures for ${from} .. ${to}`);
  say(`// Generated by scripts/humanitix/report-metrics.ts from export ${exportId}.`);
  say(`// Source for every note below:`);
  say(`//   lib/data/json/humanitix/events.json`);
  say(`//   built from ${spineFile.file}`);
  say(`//   sha256 ${spineFile.sha256}`);
  say(`//`);
  say(`// PASTE, DO NOT PIPE. Every v() note is a claim somebody signs.`);
  say();

  let totalRegistered = 0;
  let totalCheckedIn = 0;
  let instancesWithCheckIn = 0;
  const windowPeople = new Set<string>();
  const windowOrgs = new Set<string>();

  const perEvent: {
    slug: string;
    key: string;
    registered: number;
    checkedIn: number | null;
    returning: number;
    companies: number;
    topCompanies: [string, number][];
  }[] = [];

  for (const instance of window) {
    const rows = rowsByInstance.get(instance.key) ?? [];
    const slug = slugFor(instance.key);

    let returning = 0;
    const orgs = new Map<string, number>();
    for (const row of rows) {
      const email = (row["Email"] || row["Buyer email"] || "").trim().toLowerCase();
      if (email) {
        windowPeople.add(email);
        if ((firstSeen.get(email) ?? instance.eventDate) < instance.eventDate) {
          returning++;
        }
      }
      const orgId = canonicalOrganisationId(row["Company/Organisation"] ?? "");
      if (orgId) {
        orgs.set(orgId, (orgs.get(orgId) ?? 0) + 1);
        windowOrgs.add(orgId);
      }
    }

    totalRegistered += instance.registered;
    if (instance.checkInDataPresent) {
      totalCheckedIn += instance.checkedIn;
      instancesWithCheckIn++;
    }

    perEvent.push({
      slug: slug ?? instance.key,
      key: instance.key,
      registered: instance.registered,
      checkedIn: instance.checkInDataPresent ? instance.checkedIn : null,
      returning,
      companies: orgs.size,
      topCompanies: [...orgs].sort((a, b) => b[1] - a[1]).slice(0, 6),
    });
  }

  const note = (text: string) => `"${text.replace(/"/g, '\\"')}"`;
  const source = `lib/data/json/humanitix/events.json (export ${exportId}, spine sha256 ${spineFile.sha256.slice(0, 16)}…)`;

  say("// ---- headline ----");
  say(`registered: v(`);
  say(`  ${totalRegistered},`);
  say(
    `  ${note(`Sum of \`registered\` across the ${window.length} Humanitix instances dated ${from}..${to}. Source: ${source}.`)},`
  );
  say(`),`);
  say(`checked-in: v(`);
  say(`  ${totalCheckedIn},`);
  say(
    `  ${note(`Sum of \`checkedIn\` across the ${instancesWithCheckIn} of ${window.length} instances that ran a check-in. The remaining ${window.length - instancesWithCheckIn} recorded none, so this is not a total over all ${window.length}. Source: ${source}.`)},`
  );
  say(`),`);
  say(`avg-registered: v(`);
  say(`  ${Math.round(totalRegistered / window.length)},`);
  say(
    `  ${note(`${totalRegistered} ÷ ${window.length} events. Source: ${source}.`)},`
  );
  say(`),`);
  say(`companies: v(`);
  say(`  ${windowOrgs.size},`);
  say(
    `  ${note(`Distinct canonical employers among attendees who answered the Company/Organisation question, normalised by lib/data/json/humanitix/organisations.json. Self-reported at checkout and never verified. Source: ${source}.`)},`
  );
  say(`),`);
  say();
  say(`// Unique people across the window: ${windowPeople.size} (tickets: ${totalRegistered}).`);
  say();

  say("// ---- per event ----");
  for (const event of perEvent) {
    say(`${event.slug}: (`);
    say(`  registered: v(`);
    say(`    ${event.registered},`);
    say(`    ${note(`Humanitix instance ${event.key}. Source: ${source}.`)},`);
    say(`  ),`);
    if (event.checkedIn === null) {
      say(`  // NO CHECK-IN WAS RUN at this session. There is no checked-in figure —`);
      say(`  // not zero. Leave this metric unverified, or state "not recorded".`);
      say(`  checked-in: p(0),`);
    } else {
      say(`  checked-in: v(`);
      say(`    ${event.checkedIn},`);
      say(`    ${note(`Humanitix instance ${event.key}. Source: ${source}.`)},`);
      say(`  ),`);
    }
    say(`  returning: v(`);
    say(`    ${event.returning},`);
    say(
      `    ${note(`Attendees whose first She Sharp registration in the archive predates this event. Counts repeat REGISTRATION; the archive holds nothing before 2020. Source: ${source}.`)},`
    );
    say(`  ),`);
    say(`  companies: v(`);
    say(`    ${event.companies},`);
    say(`    ${note(`Distinct canonical employers among those who answered. Source: ${source}.`)},`);
    say(`  ),`);
    say(`),`);
    say(
      `// top employers: ${event.topCompanies.map(([id, n]) => `${id} (${n})`).join(", ")}`
    );
    say();
  }

  const outDir = join(REPO_ROOT, "tmp", "humanitix");
  mkdirSync(outDir, { recursive: true });
  const path = join(outDir, "report-data-suggestions.typ");
  writeFileSync(path, lines.join("\n") + "\n", "utf8");

  console.log(`Wrote ${path}`);
  console.log(`  window        ${from} .. ${to}`);
  console.log(`  events        ${window.length}`);
  console.log(`  registered    ${totalRegistered}`);
  console.log(
    `  checked in    ${totalCheckedIn}  (across ${instancesWithCheckIn} of ${window.length} instances)`
  );
  console.log(`  companies     ${windowOrgs.size}`);
  console.log(`  unique people ${windowPeople.size}`);
  const noCheckIn = perEvent.filter((event) => event.checkedIn === null);
  if (noCheckIn.length > 0) {
    console.log(
      `\n  ${noCheckIn.length} event(s) ran no check-in and have NO checked-in figure:`
    );
    for (const event of noCheckIn) console.log(`    ${event.slug}`);
    console.log("  Do not write 0 for these.");
  }
  console.log("\nNothing under report/ was written.");
}

main();
