/**
 * Computes the Humanitix figures the H1 2026 funder report is waiting on, and
 * writes them out as paste-ready Typst.
 *
 * `report/data/report-data.typ` currently carries `registered: e(408)`,
 * `checked-in: e(297)`, `companies: p(96)` and two dozen per-event placeholders,
 * each with a note saying "Replace with the Humanitix export before FINAL" —
 * and `report/build.ps1 -Final` refuses to build while any of them is
 * unverified. This produces the replacements.
 *
 * It PRINTS rather than edits. `report-data.typ` is the report's single swap
 * surface and every `v()` note is an editorial claim somebody signs; a script
 * that rewrote it would be asserting provenance on a person's behalf. The
 * output goes to `tmp/humanitix/` for a human to read and paste.
 *
 * Two figures it deliberately refuses to produce: the two Youth Tech sessions
 * ran no check-in, so their `checked-in` has no value — not 0 — and the script
 * emits a comment saying so rather than a number that would read as "nobody
 * came to a workshop that demonstrably happened".
 *
 * Usage:
 *   npx tsx scripts/humanitix/report-metrics.ts
 *   npx tsx scripts/humanitix/report-metrics.ts --from 2026-01-01 --to 2026-06-30
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import {
  canonicalOrganisationId,
  getHumanitixInstances,
  humanitixCrosswalk,
  humanitixInstanceKey,
  humanitixManifest,
  normalizeHumanitixText,
} from "../../lib/data/humanitix";
import { parseDmyToIso, parseIntStrict, parseMoneyCents, readCsv } from "./csv";
import { REPO_ROOT, argValue, vaultExists } from "./vault";

/**
 * The returning-attendee count and the per-event employer lists need per-person
 * and per-employer rows, which the committed archive deliberately does not
 * carry. So this script needs the vault — which is correct: a funder-report
 * figure should be computed from the source, once, by somebody who has it.
 */
function requireVault(exportId: string) {
  if (!vaultExists(exportId)) {
    console.error(
      `This script needs the raw export. Vault not found for ${exportId}.\n` +
        `  Set HUMANITIX_VAULT_DIR or place the CSVs in private/humanitix/${exportId}/.\n` +
        `  The committed archive holds aggregates only; the returning-attendee count\n` +
        `  and the employer lists come from the attendee rows and are never stored.`
    );
    process.exit(1);
  }
}

function main() {
  const argv = process.argv.slice(2);
  const from = argValue(argv, "--from") ?? "2026-01-01";
  const to = argValue(argv, "--to") ?? "2026-06-30";
  const exportId =
    argValue(argv, "--export") ?? humanitixManifest.exports.at(-1)?.exportId ?? "";

  requireVault(exportId);

  const spineFile = humanitixManifest.exports
    .find((entry) => entry.exportId === exportId)
    ?.files.find((file) => file.role === "spine");
  if (!spineFile) throw new Error(`No spine file recorded for export ${exportId}`);

  const spine = readCsv(exportId, spineFile.file);

  // First appearance per person, across the WHOLE archive — "returning" means
  // returning to She Sharp, not returning within the reporting window.
  const firstSeen = new Map<string, string>();
  for (const row of spine) {
    const email = (row["Email"] || row["Buyer email"] || "").trim().toLowerCase();
    if (!email) continue;
    const date = parseDmyToIso(row["Event date"] ?? "");
    const seen = firstSeen.get(email);
    if (!seen || date < seen) firstSeen.set(email, date);
  }

  const rowsByInstance = new Map<string, typeof spine>();
  for (const row of spine) {
    const key = humanitixInstanceKey(
      normalizeHumanitixText(row["Event"] ?? ""),
      parseDmyToIso(row["Event date"] ?? "")
    );
    rowsByInstance.set(key, [...(rowsByInstance.get(key) ?? []), row]);
  }

  const slugFor = (key: string) =>
    humanitixCrosswalk.links.find((link) => link.humanitixKey === key)?.siteSlug ??
    humanitixCrosswalk.series.find((series) => series.sessionKeys.includes(key))
      ?.siteSlug ??
    null;

  const window = getHumanitixInstances().filter(
    (instance) => instance.eventDate >= from && instance.eventDate <= to
  );

  const lines: string[] = [];
  const say = (text = "") => lines.push(text);

  say(`// Humanitix figures for ${from} .. ${to}`);
  say(`// Generated by scripts/humanitix/report-metrics.ts from export ${exportId}.`);
  say(`// Source for every note below:`);
  say(`//   lib/data/json/humanitix/events.json`);
  say(`//   built from ${spineFile.file}`);
  say(`//   sha256 ${spineFile.sha256}`);
  say(`//`);
  say(`// PASTE, DO NOT PIPE. Every v() note is a claim somebody signs.`);
  say();

  let totalRegistered = 0;
  let totalCheckedIn = 0;
  let instancesWithCheckIn = 0;
  const windowPeople = new Set<string>();
  const windowOrgs = new Set<string>();

  const perEvent: {
    slug: string;
    key: string;
    registered: number;
    checkedIn: number | null;
    returning: number;
    companies: number;
    topCompanies: [string, number][];
  }[] = [];

  for (const instance of window) {
    const rows = rowsByInstance.get(instance.key) ?? [];
    const slug = slugFor(instance.key);

    let returning = 0;
    const orgs = new Map<string, number>();
    for (const row of rows) {
      const email = (row["Email"] || row["Buyer email"] || "").trim().toLowerCase();
      if (email) {
        windowPeople.add(email);
        if ((firstSeen.get(email) ?? instance.eventDate) < instance.eventDate) {
          returning++;
        }
      }
      const orgId = canonicalOrganisationId(row["Company/Organisation"] ?? "");
      if (orgId) {
        orgs.set(orgId, (orgs.get(orgId) ?? 0) + 1);
        windowOrgs.add(orgId);
      }
    }

    totalRegistered += instance.registered;
    if (instance.checkInDataPresent) {
      totalCheckedIn += instance.checkedIn;
      instancesWithCheckIn++;
    }

    perEvent.push({
      slug: slug ?? instance.key,
      key: instance.key,
      registered: instance.registered,
      checkedIn: instance.checkInDataPresent ? instance.checkedIn : null,
      returning,
      companies: orgs.size,
      topCompanies: [...orgs].sort((a, b) => b[1] - a[1]).slice(0, 6),
    });
  }

  const note = (text: string) => `"${text.replace(/"/g, '\\"')}"`;
  const source = `lib/data/json/humanitix/events.json (export ${exportId}, spine sha256 ${spineFile.sha256.slice(0, 16)}…)`;

  say("// ---- headline ----");
  say(`registered: v(`);
  say(`  ${totalRegistered},`);
  say(
    `  ${note(`Sum of \`registered\` across the ${window.length} Humanitix instances dated ${from}..${to}. Source: ${source}.`)},`
  );
  say(`),`);
  say(`checked-in: v(`);
  say(`  ${totalCheckedIn},`);
  say(
    `  ${note(`Sum of \`checkedIn\` across the ${instancesWithCheckIn} of ${window.length} instances that ran a check-in. The remaining ${window.length - instancesWithCheckIn} recorded none, so this is not a total over all ${window.length}. Source: ${source}.`)},`
  );
  say(`),`);
  say(`avg-registered: v(`);
  say(`  ${Math.round(totalRegistered / window.length)},`);
  say(
    `  ${note(`${totalRegistered} ÷ ${window.length} events. Source: ${source}.`)},`
  );
  say(`),`);
  say(`companies: v(`);
  say(`  ${windowOrgs.size},`);
  say(
    `  ${note(`Distinct canonical employers among attendees who answered the Company/Organisation question, normalised by lib/data/json/humanitix/organisations.json. Self-reported at checkout and never verified. Source: ${source}.`)},`
  );
  say(`),`);
  say();
  say(`// Unique people across the window: ${windowPeople.size} (tickets: ${totalRegistered}).`);
  say();

  // ── Money and access ──────────────────────────────────────────────────────
  //
  // The report has carried an entire invented finance page since it was
  // written, while these figures sat unread in the archive it already ships.
  // They are small — the organisation runs on free places and partner in-kind
  // support, not on ticket revenue — and being small is the finding.
  //
  // Two definitions worth keeping straight, because getting either wrong turns
  // a modest true number into a wrong one:
  //   * `earnings` is NET TO SHE SHARP after Humanitix fees. Not gross, and not
  //     what an attendee paid.
  //   * `capacity` here comes from the Event summary report — the seats the
  //     event actually offered. The per-ticket-type capacities in events.json
  //     sum to something larger, because allocations overlap.
  const ticketEarnings = window.reduce((sum, i) => sum + i.earnings, 0);
  const donationAmount = window.reduce((sum, i) => sum + i.donations.amount, 0);
  const donationOrders = window.reduce((sum, i) => sum + i.donations.orders, 0);
  const orderCount = window.reduce((sum, i) => sum + i.orders, 0);

  // Seats offered comes from the Event summary report, NOT from
  // `instance.capacity`. That field sums the per-ticket-type capacities, and
  // allocations overlap — it reports 868 seats for a half-year that offered
  // 606, which would understate a 77% fill as 54%.
  const summaryFile = humanitixManifest.exports
    .find((entry) => entry.exportId === exportId)
    ?.files.find((file) => file.file.startsWith("events-report-"));
  if (!summaryFile) throw new Error(`No Event summary report in export ${exportId}`);
  const summaryRows = readCsv(exportId, summaryFile.file);
  const seatsOffered = summaryRows
    .filter((row) => {
      const date = parseDmyToIso(row["Date"] ?? "");
      return date >= from && date <= to;
    })
    .reduce((sum, row) => sum + parseIntStrict(row["Capacity"]), 0);

  // A ticket type that took money is a paid allocation; everything else was
  // given away. The six revenue-taking types in H1 2026 account for exactly the
  // ticket earnings above, so the split reconciles rather than being asserted.
  let paidTickets = 0;
  let freeTickets = 0;
  for (const instance of window) {
    for (const type of instance.ticketTypes) {
      if (type.earnings > 0) paidTickets += type.tickets;
      else freeTickets += type.tickets;
    }
  }

  const segments = new Map<string, number>();
  for (const instance of window) {
    for (const type of instance.ticketTypes) {
      segments.set(type.segment, (segments.get(type.segment) ?? 0) + type.tickets);
    }
  }

  const money = (value: number) => value.toFixed(2);

  say("// ---- money and access ----");
  say(`ticket-earnings: v(`);
  say(`  ${money(ticketEarnings)},`);
  say(
    `  ${note(`Ticket earnings across the ${window.length} Humanitix instances dated ${from}..${to}, NET TO SHE SHARP after Humanitix fees — not gross and not what attendees paid. Only ${window.filter((i) => i.earnings > 0).length} of the ${window.length} events charged for any ticket at all. Source: ${source}.`)},`
  );
  say(`),`);
  say(`donation-income: v(`);
  say(`  ${money(donationAmount)},`);
  say(
    `  ${note(`${donationOrders} voluntary donations added at checkout across the window, on the Humanitix booking form. Source: ${source}.`)},`
  );
  say(`),`);
  say(`event-income: v(`);
  say(`  ${money(ticketEarnings + donationAmount)},`);
  say(
    `  ${note(`Ticket earnings plus checkout donations, ${from}..${to}. This is the whole of the income that passes through the booking platform; grant funding, sponsorship and in-kind support do not, and are not in this figure. Source: ${source}.`)},`
  );
  say(`),`);
  say(`orders: v(`);
  say(`  ${orderCount},`);
  say(
    `  ${note(`Completed Humanitix orders across the window. An order may carry more than one ticket. Source: ${source}.`)},`
  );
  say(`),`);
  say(`free-places: v(`);
  say(`  ${freeTickets},`);
  say(
    `  ${note(`Tickets issued under a ticket type that took no money, ${from}..${to} — ${Math.round((freeTickets / (freeTickets + paidTickets)) * 100)}% of all ${freeTickets + paidTickets} places. Source: ${source}.`)},`
  );
  say(`),`);
  say(`paid-places: v(`);
  say(`  ${paidTickets},`);
  say(
    `  ${note(`Tickets issued under a ticket type that took money. These ${paidTickets} places account for the whole of the ticket earnings above. Source: ${source}.`)},`
  );
  say(`),`);
  say(`seats-offered: v(`);
  say(`  ${seatsOffered},`);
  say(
    `  ${note(`Capacity summed across the ${window.length} instances, from the Humanitix Event summary report. ${totalRegistered} of those ${seatsOffered} places were taken. One event sold beyond its stated capacity. Source: ${source}.`)},`
  );
  say(`),`);

  // Payouts are the cash that actually reached the bank account. Quoted beside
  // earnings because the two do not match — the 15 May event earned $394.51 and
  // settled $351.71 — and a funder who reconciles them should find the gap
  // already named rather than discover it.
  const payoutFile = humanitixManifest.exports
    .find((entry) => entry.exportId === exportId)
    ?.files.find((file) => file.file.startsWith("payout-report-"));
  if (!payoutFile) throw new Error(`No payout report in export ${exportId}`);
  const payouts = readCsv(exportId, payoutFile.file).filter((row) => {
    const date = parseDmyToIso(row["Event Date"] ?? "");
    return date >= from && date <= to;
  });
  const payoutTotal = payouts.reduce(
    (sum, row) => sum + parseMoneyCents(row["Payout Amount"]) / 100,
    0
  );

  say(`payouts-settled: v(`);
  say(`  ${payouts.length},`);
  say(
    `  ${note(`Humanitix settlements for events in ${from}..${to}, all of which were also paid within the window. Source: the payout report in export ${exportId}.`)},`
  );
  say(`),`);
  say(`payouts-amount: v(`);
  say(`  ${money(payoutTotal)},`);
  say(
    `  ${note(`Total settled to She Sharp for events in the window. It is ${money(ticketEarnings + donationAmount - payoutTotal)} less than recorded earnings; the difference is an adjustment on one event that the payout report does not itemise. Source: the payout report in export ${exportId}.`)},`
  );
  say(`),`);
  say();
  say(`// ticket segments (sums to ${[...segments.values()].reduce((a, b) => a + b, 0)}):`);
  for (const [segment, tickets] of [...segments].sort((a, b) => b[1] - a[1])) {
    say(`//   ${String(tickets).padStart(4)}  ${segment}`);
  }
  say();

  say("// ---- per event ----");
  for (const event of perEvent) {
    say(`${event.slug}: (`);
    say(`  registered: v(`);
    say(`    ${event.registered},`);
    say(`    ${note(`Humanitix instance ${event.key}. Source: ${source}.`)},`);
    say(`  ),`);
    if (event.checkedIn === null) {
      say(`  // NO CHECK-IN WAS RUN at this session. There is no checked-in figure —`);
      say(`  // not zero. na() renders an em dash and survives a FINAL build,`);
      say(`  // because "not recorded" is a fact about the measurement, not a gap`);
      say(`  // in it. Never write 0 here: it reads as nobody coming.`);
      say(`  checked-in: na(`);
      say(`    ${note(`NOT RECORDED. This session ran no check-in, so Humanitix scanned nobody. ${event.registered} people registered. Source: ${source}.`)},`);
      say(`  ),`);
    } else {
      say(`  checked-in: v(`);
      say(`    ${event.checkedIn},`);
      say(`    ${note(`Humanitix instance ${event.key}. Source: ${source}.`)},`);
      say(`  ),`);
    }
    say(`  returning: v(`);
    say(`    ${event.returning},`);
    say(
      `    ${note(`Attendees whose first She Sharp registration in the archive predates this event. Counts repeat REGISTRATION; the archive holds nothing before 2020. Source: ${source}.`)},`
    );
    say(`  ),`);
    say(`  companies: v(`);
    say(`    ${event.companies},`);
    say(`    ${note(`Distinct canonical employers among those who answered. Source: ${source}.`)},`);
    say(`  ),`);
    say(`),`);
    say(
      `// top employers: ${event.topCompanies.map(([id, n]) => `${id} (${n})`).join(", ")}`
    );
    say();
  }

  const outDir = join(REPO_ROOT, "tmp", "humanitix");
  mkdirSync(outDir, { recursive: true });
  const path = join(outDir, "report-data-suggestions.typ");
  writeFileSync(path, lines.join("\n") + "\n", "utf8");

  console.log(`Wrote ${path}`);
  console.log(`  window        ${from} .. ${to}`);
  console.log(`  events        ${window.length}`);
  console.log(`  registered    ${totalRegistered}`);
  console.log(
    `  checked in    ${totalCheckedIn}  (across ${instancesWithCheckIn} of ${window.length} instances)`
  );
  console.log(`  companies     ${windowOrgs.size}`);
  console.log(`  unique people ${windowPeople.size}`);
  console.log(`  event income  ${(ticketEarnings + donationAmount).toFixed(2)} (tickets ${ticketEarnings.toFixed(2)} + donations ${donationAmount.toFixed(2)})`);
  console.log(`  places        ${paidTickets} paid / ${freeTickets} free of ${seatsOffered} offered`);
  console.log(`  payouts       ${payouts.length} settlements, ${payoutTotal.toFixed(2)}`);
  const noCheckIn = perEvent.filter((event) => event.checkedIn === null);
  if (noCheckIn.length > 0) {
    console.log(
      `\n  ${noCheckIn.length} event(s) ran no check-in and have NO checked-in figure:`
    );
    for (const event of noCheckIn) console.log(`    ${event.slug}`);
    console.log("  Do not write 0 for these.");
  }
  console.log("\nNothing under report/ was written.");
}

main();
