/**
 * Prints the largest organisations represented at each event, as paste-ready
 * Typst for the `companies:` lists in `report/data/events.typ`.
 *
 * Kept apart from `report-metrics.ts` because it answers a different question:
 * that one produces the metric tree, this one produces a display list whose
 * rows are organisation NAMES, and a name in a funder report is a claim about a
 * third party. A wrong count is an error; a wrong employer beside somebody's
 * event is a different kind of problem.
 *
 * It prints rather than edits, for the same reason as `report-metrics.ts`.
 *
 * Usage:
 *   npx tsx scripts/humanitix/top-employers.ts --from 2026-01-01 --to 2026-06-30
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import {
  canonicalOrganisationId,
  getHumanitixInstances,
  isPersonalName,
  personNameKey,
  humanitixCrosswalk,
  humanitixInstanceKey,
  humanitixManifest,
  humanitixOrganisations,
  normalizeHumanitixText,
} from "../../lib/data/humanitix";
import { parseDmyToIso, readCsv } from "./csv";
import { REPO_ROOT, argValue, vaultExists } from "./vault";

/** How many rows the event page's table can hold before it stops being a slice. */
const TOP_N = 12;

function main() {
  const argv = process.argv.slice(2);
  const from = argValue(argv, "--from") ?? "2026-01-01";
  const to = argValue(argv, "--to") ?? "2026-06-30";
  const exportId =
    argValue(argv, "--export") ?? humanitixManifest.exports.at(-1)?.exportId ?? "";

  if (!vaultExists(exportId)) {
    console.error(
      `This script needs the raw export — the committed archive stores employer\n` +
        `counts only in aggregate, never per event. Vault not found for ${exportId}.`
    );
    process.exit(1);
  }

  const spineFile = humanitixManifest.exports
    .find((entry) => entry.exportId === exportId)
    ?.files.find((file) => file.role === "spine");
  if (!spineFile) throw new Error(`No spine file recorded for export ${exportId}`);

  const rows = readCsv(exportId, spineFile.file);
  const byInstance = new Map<string, typeof rows>();
  for (const row of rows) {
    const key = humanitixInstanceKey(
      normalizeHumanitixText(row["Event"] ?? ""),
      parseDmyToIso(row["Event date"] ?? "")
    );
    byInstance.set(key, [...(byInstance.get(key) ?? []), row]);
  }

  // Six attendees typed their own name into the Company/Organisation box. This
  // table is printed in a document that goes to funders, so a personal name
  // reaching it would publish an individual as an "organisation represented".
  // Indexing the names present in this export makes that detectable rather than
  // a matter of noticing.
  const personNameKeys = new Set<string>();
  for (const row of rows) {
    for (const [first, last] of [
      [row["First name"], row["Last name"]],
      [row["First Name"], row["Last Name"]],
      [row["Buyer first name"], row["Buyer last name"]],
    ] as [string | undefined, string | undefined][]) {
      const key = personNameKey(first ?? "", last ?? "");
      if (key) personNameKeys.add(key);
    }
  }

  /**
   * For an organisation with no entry in `organisations.json`, the display name
   * is the spelling attendees used most often across the whole archive — not a
   * slug, and not a guess.
   *
   * That distinction matters for a document going to funders. A slug
   * (`fisher-and-paykel-healthcare`) is unpublishable and a title-cased guess
   * would be an invention; the modal raw spelling is a quotable fact about what
   * people wrote in the box, which is exactly what the accompanying note claims
   * it is.
   */
  const rawSpellings = new Map<string, Map<string, number>>();
  for (const row of rows) {
    const raw = normalizeHumanitixText(row["Company/Organisation"] ?? "");
    if (!raw || isPersonalName(raw, personNameKeys)) continue;
    const id = canonicalOrganisationId(raw);
    if (!id) continue;
    const tally = rawSpellings.get(id) ?? new Map<string, number>();
    tally.set(raw, (tally.get(raw) ?? 0) + 1);
    rawSpellings.set(id, tally);
  }

  const declaredName = (id: string) =>
    humanitixOrganisations.canonical.find((entry) => entry.id === id)?.name ?? null;

  const modalSpelling = (id: string) =>
    [...(rawSpellings.get(id) ?? new Map())].sort((a, b) =>
      b[1] === a[1] ? a[0].localeCompare(b[0]) : b[1] - a[1]
    )[0]?.[0] ?? id;

  const lines: string[] = [];
  const say = (text = "") => lines.push(text);

  say(`// Largest organisations represented, ${from} .. ${to}`);
  say(`// Generated by scripts/humanitix/top-employers.ts from export ${exportId}.`);
  say(`// Paste into the \`companies:\` list of the matching event in events.typ.`);
  say(`//`);
  say(`// Rows marked "as typed" have no entry in organisations.json, so their`);
  say(`// label is the spelling attendees used most often — a fact about the box`);
  say(`// they filled in, not a verified company name. Everything else is the`);
  say(`// canonical name from organisations.json. Either way this table names`);
  say(`// third parties in a document that goes to funders: read every row.`);
  say();

  for (const instance of getHumanitixInstances()) {
    if (instance.eventDate < from || instance.eventDate > to) continue;

    const slug =
      humanitixCrosswalk.links.find((link) => link.humanitixKey === instance.key)
        ?.siteSlug ?? instance.key;

    const tally = new Map<string, number>();
    let personal = 0;
    for (const row of byInstance.get(instance.key) ?? []) {
      const raw = row["Company/Organisation"] ?? "";
      if (isPersonalName(raw, personNameKeys)) {
        personal += 1;
        continue;
      }
      const id = canonicalOrganisationId(raw);
      if (!id) continue;
      tally.set(id, (tally.get(id) ?? 0) + 1);
    }

    const ranked = [...tally].sort((a, b) =>
      b[1] === a[1] ? a[0].localeCompare(b[0]) : b[1] - a[1]
    );
    const shown = ranked.slice(0, TOP_N);
    const shownTickets = shown.reduce((total, [, count]) => total + count, 0);
    const allTickets = ranked.reduce((total, [, count]) => total + count, 0);

    say(`// ---- ${slug} (${instance.eventDate}) ----`);
    say(
      `// ${ranked.length} organisations across ${allTickets} answered rows of ${instance.registered} registrations.`
    );
    say(
      `// The ${shown.length} rows below cover ${shownTickets} of those — a top-N slice, not a full account.`
    );
    if (personal > 0) {
      say(
        `// ${personal} row(s) here named the registrant rather than an employer and are excluded.`
      );
    }
    say(`    companies: (`);
    for (const [id, count] of shown) {
      const declared = declaredName(id);
      const label = declared ?? modalSpelling(id);
      const provenance = declared
        ? `normalised to its canonical name by lib/data/json/humanitix/organisations.json`
        : `shown as attendees most often spelled it; no canonical entry exists for it`;
      say(
        `      (${JSON.stringify(label)}, v(${count}, ${JSON.stringify(
          `Humanitix checkout Company/Organisation field, instance ${instance.key} — ${provenance}. Self-reported at checkout and never verified against the organisation.`
        )})),${declared ? "" : "  // as typed"}`
      );
    }
    say(`    ),`);
    say();
  }

  const outDir = join(REPO_ROOT, "tmp", "humanitix");
  mkdirSync(outDir, { recursive: true });
  const path = join(outDir, "top-employers.typ");
  writeFileSync(path, lines.join("\n") + "\n", "utf8");

  console.log(`Wrote ${path}`);
  console.log("Nothing under report/ was written.");
}

main();
