// AUTO-GENERATED by scripts/events/build-event-poster.ts — do not edit by hand.
//
// Promotional graphics for this event's speakers. They have no page on the
// website by design: they are posted to LinkedIn and Instagram one at a time
// over the weeks before the event, so nothing renders them. Naming them here
// rather than in scripts/verify-image-paths.ts means the forward check guards
// them too — delete one and CI fails, instead of CI staying green while a
// scheduled post loses its picture.
//
// NEVER point coverImage.url at one of these. A speaker poster has no safe
// band, so an event card would crop the person's name away.

export interface SpeakerPoster {
  file: string;
  subject: string;
  alt: string;
}

export const speakerPosters: SpeakerPoster[] = [
  {
    file: "/img/events/event-lesmills-03-september-2026/lineup-social.jpg",
    subject: "Meet the Panel",
    alt: "Meet the Panel: every speaker at No Pain, All Gain – Getting Fit for AI, on one She Sharp promotional graphic.",
  },
  {
    file: "/img/events/event-lesmills-03-september-2026/speaker-ben-sullivan-social.jpg",
    subject: "Ben Sullivan",
    alt: "Ben Sullivan — a She Sharp promotional graphic for No Pain, All Gain – Getting Fit for AI.",
  },
  {
    file: "/img/events/event-lesmills-03-september-2026/speaker-ben-sullivan-square.jpg",
    subject: "Ben Sullivan",
    alt: "Ben Sullivan — a She Sharp promotional graphic for No Pain, All Gain – Getting Fit for AI.",
  },
  {
    file: "/img/events/event-lesmills-03-september-2026/speaker-ben-sullivan-story.jpg",
    subject: "Ben Sullivan",
    alt: "Ben Sullivan — a She Sharp promotional graphic for No Pain, All Gain – Getting Fit for AI.",
  },
  {
    file: "/img/events/event-lesmills-03-september-2026/speaker-carolina-lobos-social.jpg",
    subject: "Carolina Lobos",
    alt: "Carolina Lobos — a She Sharp promotional graphic for No Pain, All Gain – Getting Fit for AI.",
  },
  {
    file: "/img/events/event-lesmills-03-september-2026/speaker-carolina-lobos-square.jpg",
    subject: "Carolina Lobos",
    alt: "Carolina Lobos — a She Sharp promotional graphic for No Pain, All Gain – Getting Fit for AI.",
  },
  {
    file: "/img/events/event-lesmills-03-september-2026/speaker-carolina-lobos-story.jpg",
    subject: "Carolina Lobos",
    alt: "Carolina Lobos — a She Sharp promotional graphic for No Pain, All Gain – Getting Fit for AI.",
  },
  {
    file: "/img/events/event-lesmills-03-september-2026/speaker-gemma-lynskey-social.jpg",
    subject: "Gemma Lynskey",
    alt: "Gemma Lynskey — a She Sharp promotional graphic for No Pain, All Gain – Getting Fit for AI.",
  },
  {
    file: "/img/events/event-lesmills-03-september-2026/speaker-gemma-lynskey-square.jpg",
    subject: "Gemma Lynskey",
    alt: "Gemma Lynskey — a She Sharp promotional graphic for No Pain, All Gain – Getting Fit for AI.",
  },
  {
    file: "/img/events/event-lesmills-03-september-2026/speaker-gemma-lynskey-story.jpg",
    subject: "Gemma Lynskey",
    alt: "Gemma Lynskey — a She Sharp promotional graphic for No Pain, All Gain – Getting Fit for AI.",
  },
  {
    file: "/img/events/event-lesmills-03-september-2026/speaker-keryn-mckenzie-social.jpg",
    subject: "Keryn McKenzie",
    alt: "Keryn McKenzie — a She Sharp promotional graphic for No Pain, All Gain – Getting Fit for AI.",
  },
  {
    file: "/img/events/event-lesmills-03-september-2026/speaker-keryn-mckenzie-square.jpg",
    subject: "Keryn McKenzie",
    alt: "Keryn McKenzie — a She Sharp promotional graphic for No Pain, All Gain – Getting Fit for AI.",
  },
  {
    file: "/img/events/event-lesmills-03-september-2026/speaker-keryn-mckenzie-story.jpg",
    subject: "Keryn McKenzie",
    alt: "Keryn McKenzie — a She Sharp promotional graphic for No Pain, All Gain – Getting Fit for AI.",
  },
];
