/**
 * optimize-images.mts — Build responsive WebP variants for the curated hero set.
 *
 * Reads a picks JSON (see scratchpad/picks-proposed.json for the shape), then for
 * each pick emits public/img/curated/{name}-{1920,1280,768}.webp (sharp, quality
 * 78, never enlarged) and writes a typed public/img/curated/index.ts exporting the
 * `curatedImages` map consumed by the design system.
 *
 * Usage:
 *   npx tsx scripts/optimize-images.mts [picksJson]
 * picksJson defaults to the scratchpad proposal; pass the confirmed file to build
 * the final set, e.g.
 *   npx tsx scripts/optimize-images.mts scripts/curated-picks.json
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const REPO = process.cwd();
// Defaults to the real asset dir; CURATED_OUT allows a throwaway dry-run target.
const OUT_DIR = process.env.CURATED_OUT
  ? path.resolve(process.env.CURATED_OUT)
  : path.join(REPO, "public/img/curated");
const QUALITY = 78;
const TARGET_WIDTHS = [1920, 1280, 768] as const;

type Pick = { path: string; name: string; alt: string; role?: string };
type PicksFile = { picks: Pick[] };

const DEFAULT_PICKS =
  "D:/Temp/claude/D--github-repository-she-sharp/849ecf8e-f8d5-42df-a44f-112fd41ba309/scratchpad/picks-proposed.json";

async function main() {
  const picksPath = process.argv[2]
    ? path.resolve(process.argv[2])
    : DEFAULT_PICKS;
  const parsed = JSON.parse(await fs.readFile(picksPath, "utf8")) as PicksFile;
  const picks = parsed.picks ?? [];
  if (!picks.length) throw new Error(`No picks found in ${picksPath}`);

  // Reject duplicate semantic names early — they would collide on disk / in the map.
  const seen = new Set<string>();
  for (const p of picks) {
    if (seen.has(p.name)) throw new Error(`Duplicate pick name: ${p.name}`);
    seen.add(p.name);
  }

  await fs.mkdir(OUT_DIR, { recursive: true });

  type Entry = {
    name: string;
    role: string;
    alt: string;
    width: number; // largest variant width
    height: number; // largest variant height
    variants: { w: number; file: string }[]; // actual emitted widths
  };
  const entries: Entry[] = [];

  for (const pick of picks) {
    const abs = path.join(REPO, pick.path);
    const img = sharp(abs);
    const meta = await img.metadata();
    const ow = meta.width ?? 0;
    const oh = meta.height ?? 0;
    if (!ow || !oh) {
      console.warn(`skip (no dims): ${pick.path}`);
      continue;
    }

    // Emit one file per label; never enlarge — cap each label at the source width.
    const variants: { w: number; file: string }[] = [];
    for (const label of TARGET_WIDTHS) {
      const w = Math.min(label, ow);
      const file = `${pick.name}-${label}.webp`;
      await sharp(abs)
        .resize({ width: w, withoutEnlargement: true })
        .webp({ quality: QUALITY })
        .toFile(path.join(OUT_DIR, file));
      variants.push({ w, file });
    }

    // Largest variant drives layout width/height.
    const top = variants[0];
    const topH = Math.round((oh * top.w) / ow);
    entries.push({
      name: pick.name,
      role: pick.role ?? "support",
      alt: pick.alt,
      width: top.w,
      height: topH,
      variants,
    });
    console.log(
      `${pick.name}: ${variants.map((v) => v.w).join("/")} from ${ow}x${oh}`,
    );
  }

  // Generate the typed index.ts.
  const body = entries
    .map((e) => {
      const srcSet = e.variants
        .map((v) => `      "${v.w}": "/img/curated/${v.file}",`)
        .join("\n");
      return `  "${e.name}": {
    src: "/img/curated/${e.variants[0].file}",
    srcSet: {
${srcSet}
    },
    width: ${e.width},
    height: ${e.height},
    role: "${e.role}",
    alt: ${JSON.stringify(e.alt)},
  },`;
    })
    .join("\n");

  const ts = `// AUTO-GENERATED by scripts/optimize-images.mts — do not edit by hand.
// Curated real-event photography for the editorial design system.

export type CuratedImage = {
  src: string;
  srcSet: Record<string, string>;
  width: number;
  height: number;
  role: "hero" | "divider" | "card" | "support";
  alt: string;
};

export const curatedImages = {
${body}
} as const satisfies Record<string, CuratedImage>;

export type CuratedImageKey = keyof typeof curatedImages;

/** Build a \`srcSet\` attribute string (width descriptors) from a curated entry. */
export function toSrcSet(img: CuratedImage): string {
  return Object.entries(img.srcSet)
    .map(([w, url]) => \`\${url} \${w}w\`)
    .join(", ");
}
`;

  await fs.writeFile(path.join(OUT_DIR, "index.ts"), ts);
  console.log(`\nwrote ${entries.length} entries -> public/img/curated/index.ts`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
