// Page 29 — methodology, sources, and (in a draft build) the placeholder register.
//
// THIS PAGE IS THE REPORT'S CREDIBILITY. A funder who finds an unexplained
// number checks the rest; a funder who finds the caveats already written down
// stops checking. So this page states what is counted, what is not, and what is
// still being reconciled — in plain words, before anyone has to ask.
//
// `placeholder-register(D)` renders a live table of every unverified metric in a
// DRAFT build and nothing at all in a FINAL one. It is generated by walking the
// data tree, so it cannot drift out of date the way a hand-maintained caveat
// list would.

#import "../theme/theme.typ": *
#import "../lib/layout.typ": sheet
#import "../lib/components.typ": source-note, eyebrow
#import "../lib/metrics.typ": placeholder-register
#import "../data/report-data.typ": D
#import "../data/copy.typ": methodology
#import "../data/sources.typ": internal-sources

// TWO pages, deliberately. The disclosure list grew past one sheet and was
// breaking mid-table — the source register split across a page boundary with its
// heading orphaned. Trimming would have meant deleting disclosure, which is the
// one thing this section exists to do, so the split is now structural: the
// narrative on the first page, the register of sources on the second.
#let methodology-page() = {
  sheet(title: "Methodology and sources")[
    #block(above: 0pt, below: 0pt, width: 100%)[
      #set par(leading: lead-body, justify: true)
      #text(size: size-body, fill: ink-700, methodology)
    ]
  ]

  sheet(title: "Where each figure comes from")[
    #block(above: 0pt, below: gap-section, width: 100%)[
    // RULE 3 — 7.5pt at 0.60em leading is 4.50pt within-item; 8pt row-gutter is
    // 1.78x. Below ~1.7x adjacent source rows merge into one grey slab.
    #grid(
      columns: (34mm, 1fr),
      column-gutter: 5mm,
      row-gutter: 8pt,
      ..internal-sources.map(s => (
        text(font: body-font, size: size-micro, weight: 700, fill: brand, s.label),
        {
          set par(leading: 0.60em)
          text(font: body-font, size: size-micro, fill: ink-700, s.detail)
        },
      )).flatten()
    )
  ]

    #source-note[
      Prepared 1 August 2026 covering 1 January to 30 June 2026. Attendance is
      taken from the event register in the She Sharp codebase; platform figures
      are read from the live member database. Where a figure could not be traced
      to either, it is marked unverified and is not used in any headline.
    ]
  ]

  // Draft only — renders nothing in a final build.
  placeholder-register(D)
}
