// =============================================================================
// She Sharp — The record so far
// =============================================================================
//
// An INTERNAL report. Its audience is the trustees and the team, and its job is
// the one the funder report cannot do: say what the systems actually recorded
// between 2019 and today, including the parts that would never go into a
// funding application.
//
// Three rules it is built on.
//
//   1. NOTHING HERE IS TYPED. Every figure comes out of
//      `report-internal/data/record.json`, which is generated by
//      `scripts/internal-report/build-record.ts` from the ticketing archive,
//      the mailing audience and the public charities register. Refreshing this
//      report against a newer export is one command, and there is no path by
//      which a number in it can disagree with its source.
//
//   2. EVERY CHART SAYS WHAT IT CANNOT SHOW. A trend drawn from a system that
//      only started in 2020, or from events that only sometimes ran a scanner,
//      is a trend in the RECORD before it is a trend in the organisation. The
//      note under each chart carries that distinction; it is not decoration.
//
//   3. NO NUMBER IS ROUNDED TOWARDS A BETTER STORY. Where the record is
//      unflattering it is printed unflattering, because the alternative is a
//      document the team cannot use to decide anything.
//
// Build:  pwsh report-internal\build.ps1 [-Png]
// =============================================================================

#import "/report/lib/layout.typ": report-setup

#import "sections/01-cover.typ": cover
#import "sections/02-what-this-is.typ": what-this-is
#import "sections/03-at-a-glance.typ": at-a-glance
#import "sections/04-reach.typ": reach
#import "sections/05-people.typ": people
#import "sections/06-attendance.typ": attendance
#import "sections/07-list.typ": list-page
#import "sections/07b-engagement.typ": engagement
#import "sections/08-money.typ": money
#import "sections/09-mentorship.typ": mentorship
#import "sections/10-claims.typ": claims
#import "sections/11-blind-spots.typ": blind-spots
#import "sections/12-questions.typ": questions

#set document(
  title: "She Sharp — the record so far (internal)",
  author: "She Sharp",
  keywords: ("She Sharp", "internal", "record", "not for circulation"),
)

#show: report-setup

// ── 1 ───────────────────────────────────────────────────────────────────────
#cover()
// ── 2 ───────────────────────────────────────────────────────────────────────
#what-this-is()
// ── 3 ───────────────────────────────────────────────────────────────────────
#at-a-glance()
// ── 4 ───────────────────────────────────────────────────────────────────────
#reach()
// ── 5 ───────────────────────────────────────────────────────────────────────
#people()
// ── 6 ───────────────────────────────────────────────────────────────────────
#attendance()
// ── 7 ───────────────────────────────────────────────────────────────────────
#list-page()
// ── 8 ───────────────────────────────────────────────────────────────────────
#engagement()
// ── 9 ─────────────────────────────────────────────────────────────────
#money()
// ── 10 ─────────────────────────────────────────────────────────────────
#mentorship()
// ── 11 ─────────────────────────────────────────────────────────────────
#claims()
// ── 12 ─────────────────────────────────────────────────────────────────
#blind-spots()
// ── 13 ─────────────────────────────────────────────────────────────────
#questions()
