/**
 * Extracts the newsletter back catalogue out of the Mailchimp vault and into
 * this repository, sanitised, one HTML file per campaign.
 *
 * WHY THIS EXISTS
 * ---------------
 * 51 of the 59 newsletter cards on `/resources/newsletters` open a page hosted
 * by Mailchimp, and the founder is cancelling the paid subscription. Mailchimp
 * documents **nothing** about what a downgrade or a pause does to those pages —
 * neither its plan-change help page nor its campaign-archive help page mentions
 * the other, checked 2026-08-30. The correct response to an unknown is the
 * cheap ordering rather than a prediction: archive first, cancel second. That
 * is `docs/deployment/MAILCHIMP_CANCELLATION.md` §3, and this is the archiving
 * half of it.
 *
 * It reads `archive_html`, not `html`; the evidence for that choice is in
 * `archive-html.ts`, which also holds every sanitisation rule and the scan the
 * CI guard re-runs over the output.
 *
 * WHAT IT WRITES
 * --------------
 *   lib/data/newsletter-archive/<campaignId>.html   179 bodies
 *   lib/data/newsletter-archive/index.json          the join key for PR 3
 *
 * NOT `lib/data/json/`. That directory holds derived *aggregates* under a CI
 * leak guard that forbids free text, and these are the newsletters themselves —
 * a different kind of thing under a different guard
 * (`scripts/mailchimp/archive-guard.test.ts`).
 *
 * GENERATED, WHOLESALE. A hand-edit is lost on the next run and is visible in
 * the meantime as a sha256 mismatch in `index.json`.
 *
 * Usage:
 *   MAILCHIMP_VAULT_DIR=…/she-sharp-slack-archive/mailchimp/2026-08-28-api \
 *     npx tsx scripts/mailchimp/extract-archive.ts --export 2026-08-28-api [--check]
 *
 * `--check` writes nothing and exits non-zero if the generated output would
 * differ from what is committed, which is the determinism test the rest of this
 * archive uses.
 */
import "dotenv/config";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import * as cheerio from "cheerio";

import {
  ARCHIVE_HTML_DIR,
  ARCHIVE_INDEX_PATH,
  buildArchiveLookup,
  resolveCampaignByArchiveUrl,
  type ArchiveIndex,
  type ArchiveIndexEntry,
} from "./archive-index";
import {
  sanitiseArchiveHtml,
  scanSanitised,
  type ArchiveImage,
  type SanitiseStats,
} from "./archive-html";
import { argValue, resolveVaultDir } from "./vault";

const DEFAULT_EXPORT = "2026-08-28-api";

/** `sent-campaigns.json`, narrowed to the fields the index needs. */
interface SentCampaign {
  id: string;
  web_id: number;
  send_time: string;
  archive_url: string | null;
  long_archive_url: string | null;
  settings: { subject_line?: string };
}

/** One row of the vault's `campaign-images.json`. */
interface CrosswalkImage {
  url: string;
  classification: ArchiveImage["classification"];
  file: string | null;
  sha256: string | null;
}

function sha256(text: string): string {
  return createHash("sha256").update(text, "utf8").digest("hex");
}

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(path, "utf8")) as T;
}

/**
 * Inserts a provenance comment at the top of `<head>`.
 *
 * Deliberately not before the doctype: a comment there puts every browser into
 * quirks mode, and these bodies are table layouts from 2019 whose rendering
 * depends on it.
 */
function withProvenance(html: string, campaign: SentCampaign, exportId: string): string {
  const $ = cheerio.load(html);
  const note =
    `\n  Archived from Mailchimp campaign ${campaign.id}, sent ${campaign.send_time}.\n` +
    `  Source: ${exportId}/content/${campaign.id}.json -> archive_html, in the private vault.\n` +
    `  GENERATED by scripts/mailchimp/extract-archive.ts. Do not hand-edit.\n` +
    `  Mailchimp footer, chrome images and recipient identifiers removed; see\n` +
    `  scripts/mailchimp/archive-html.ts for every rule and the reason for it.\n`;
  const head = $("head");
  if (head.length > 0) head.prepend(`<!--${note}-->`);
  else $.root().prepend(`<!--${note}-->`);
  return `${$.html().trimEnd()}\n`;
}

function summarise(all: SanitiseStats[]): Record<string, number> {
  const total: Record<string, number> = {};
  for (const stats of all) {
    for (const [key, value] of Object.entries(stats)) {
      total[key] = (total[key] ?? 0) + value;
    }
  }
  return total;
}

function main(): void {
  const argv = process.argv.slice(2);
  const exportId = argValue(argv, "--export") ?? DEFAULT_EXPORT;
  const checkOnly = argv.includes("--check");

  const vault = resolveVaultDir(exportId);
  const contentDir = join(vault, "content");
  if (!existsSync(contentDir)) {
    throw new Error(
      `${contentDir} does not exist.\n` +
        `  This script needs an API pull that included \`content\` — see\n` +
        `  docs/development/MAILCHIMP_ARCHIVE.md, "What the API pull holds".`
    );
  }

  const campaigns = readJson<SentCampaign[]>(join(vault, "sent-campaigns.json"));
  const crosswalk = readJson<{ images: CrosswalkImage[] }>(join(vault, "campaign-images.json"));

  // The crosswalk is keyed by the URL exactly as it appears in a body, which is
  // what `<img src>` gives back once cheerio has decoded the entities.
  const imageByUrl = new Map<string, ArchiveImage>(
    crosswalk.images.map((image) => [
      image.url,
      { classification: image.classification, file: image.file, sha256: image.sha256 },
    ])
  );

  const lookup = buildArchiveLookup(
    campaigns.map((campaign) => ({
      id: campaign.id,
      webId: campaign.web_id,
      archiveUrl: campaign.archive_url,
      longArchiveUrl: campaign.long_archive_url,
    }))
  );

  const entries: ArchiveIndexEntry[] = [];
  const withoutBody: string[] = [];
  const allStats: SanitiseStats[] = [];
  const generated = new Map<string, string>();

  // Sorted by id so the index and the on-disk set are the same on every machine.
  for (const campaign of [...campaigns].sort((a, b) => (a.id < b.id ? -1 : 1))) {
    const path = join(contentDir, `${campaign.id}.json`);
    if (!existsSync(path)) {
      withoutBody.push(campaign.id);
      continue;
    }
    const body = readJson<{ archive_html?: string }>(path).archive_html ?? "";
    if (body.trim() === "") {
      withoutBody.push(campaign.id);
      continue;
    }

    const { html, stats } = sanitiseArchiveHtml(body, {
      campaignId: campaign.id,
      imageByUrl: (url) => imageByUrl.get(url),
      campaignIdForArchiveUrl: (url) => resolveCampaignByArchiveUrl(lookup, url),
    });
    allStats.push(stats);

    const file = withProvenance(html, campaign, exportId);

    // The extractor refuses to write what the guard would reject. Failing here
    // names the campaign; failing in CI names only the file, three commits later.
    const violations = scanSanitised(file);
    if (violations.length > 0) {
      throw new Error(
        `campaign ${campaign.id} still violates the archive rules after sanitising:\n` +
          violations.map((v) => `    ${v.rule}: ${v.detail}`).join("\n")
      );
    }

    const subject = campaign.settings.subject_line ?? "";
    generated.set(`${campaign.id}.html`, file);
    entries.push({
      id: campaign.id,
      webId: campaign.web_id,
      sendTime: campaign.send_time,
      subject,
      archiveUrl: campaign.archive_url,
      longArchiveUrl: campaign.long_archive_url,
      file: `${campaign.id}.html`,
      bytes: Buffer.byteLength(file, "utf8"),
      sha256: sha256(file),
    });
  }

  const index: ArchiveIndex = {
    sourceExport: exportId,
    campaignsSent: campaigns.length,
    campaignsArchived: entries.length,
    campaignsWithoutBody: withoutBody.sort(),
    entries,
  };
  const indexText = `${JSON.stringify(index, null, 2)}\n`;

  // A subject line is free text and reaches the site as a card title, so it
  // goes through the same address scan as a body rather than being trusted for
  // being short.
  const indexViolations = scanSanitised(indexText, "index");
  if (indexViolations.length > 0) {
    throw new Error(
      "index.json violates the archive rules:\n" +
        indexViolations.map((v) => `    ${v.rule}: ${v.detail}`).join("\n")
    );
  }

  const existing = existsSync(ARCHIVE_HTML_DIR)
    ? readdirSync(ARCHIVE_HTML_DIR).filter((name) => name.endsWith(".html"))
    : [];
  const stale = existing.filter((name) => !generated.has(name));

  const changed: string[] = [];
  for (const [name, text] of generated) {
    const path = join(ARCHIVE_HTML_DIR, name);
    if (!existsSync(path) || readFileSync(path, "utf8") !== text) changed.push(name);
  }
  const indexChanged =
    !existsSync(ARCHIVE_INDEX_PATH) || readFileSync(ARCHIVE_INDEX_PATH, "utf8") !== indexText;

  const totals = summarise(allStats);
  console.log(`export:               ${exportId}`);
  console.log(`campaigns sent:       ${campaigns.length}`);
  console.log(`bodies archived:      ${entries.length}`);
  console.log(`no body at all:       ${withoutBody.length}${withoutBody.length > 0 ? ` (${withoutBody.join(", ")})` : ""}`);
  console.log(`total bytes:          ${entries.reduce((sum, e) => sum + e.bytes, 0)}`);
  console.log("");
  for (const [key, value] of Object.entries(totals).sort()) {
    console.log(`  ${key.padEnd(24)} ${value}`);
  }
  console.log("");

  if (checkOnly) {
    if (changed.length === 0 && stale.length === 0 && !indexChanged) {
      console.log("no changes — the committed archive matches the vault");
      return;
    }
    console.error(
      `${changed.length} file(s) would change, ${stale.length} would be deleted` +
        `${indexChanged ? ", index.json would change" : ""}:\n` +
        [...changed.slice(0, 20), ...stale.slice(0, 20).map((s) => `${s} (stale)`)]
          .map((name) => `    ${name}`)
          .join("\n")
    );
    process.exit(1);
  }

  mkdirSync(ARCHIVE_HTML_DIR, { recursive: true });
  for (const [name, text] of generated) {
    writeFileSync(join(ARCHIVE_HTML_DIR, name), text, "utf8");
  }
  for (const name of stale) {
    rmSync(join(ARCHIVE_HTML_DIR, name));
  }
  writeFileSync(ARCHIVE_INDEX_PATH, indexText, "utf8");

  console.log(`wrote ${generated.size} file(s) to ${ARCHIVE_HTML_DIR}`);
  if (stale.length > 0) console.log(`removed ${stale.length} stale file(s)`);
  console.log(`wrote ${ARCHIVE_INDEX_PATH}`);
}

try {
  main();
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
}
