/**
 * Computes the Mailchimp figures the H1 2026 funder report needs, and writes
 * them out as paste-ready Typst.
 *
 * The twin of `scripts/humanitix/report-metrics.ts`, and deliberately built the
 * same way: it PRINTS rather than edits. `report/data/report-data.typ` is the
 * report's single swap surface and every `v()` note is an editorial claim
 * somebody signs; a script that rewrote it would be asserting provenance on a
 * person's behalf. The output goes to `tmp/mailchimp/` for a human to read.
 *
 * It needs the vault. The committed archive (`lib/data/json/mailchimp/`) holds
 * whole-file aggregates — `byOptinYear` is per YEAR, so 2026 mixes the half-year
 * being reported with the six weeks after it. A half-year figure has to come
 * from the timestamps on the rows, which are never committed.
 *
 * Three things it derives that no other source in this repository can:
 *
 *   1. The H1 flow — joins, unsubscribes and hard-bounce removals — rather than
 *      the standing total. A list that grew and a list that shrank both report
 *      "1,560 subscribed" at the end of the period.
 *   2. Which campaigns are EVIDENCED to have been sent. Mailchimp records the
 *      campaign a person left through (`UNSUB_CAMPAIGN_TITLE`) and the campaign
 *      a bounce was detected on (`CLEAN_CAMPAIGN_TITLE`). A campaign only
 *      appears if at least one recipient unsubscribed or bounced, so the count
 *      is a FLOOR, never a total — and the script says so in the note it emits.
 *      This is the only send evidence in reach of this repository:
 *      `lib/newsletter/schedule.ts` computes a send slot, not a record of a send.
 *   3. Location coverage, stated with its own hole: 42% of subscribed contacts
 *      carry no country at all, so any geographic claim has to name that first.
 *
 * Usage:
 *   npx tsx scripts/mailchimp/report-metrics.ts
 *   npx tsx scripts/mailchimp/report-metrics.ts --from 2026-01-01 --to 2026-06-30
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { readCsv } from "./csv";
import { REPO_ROOT, argValue, vaultExists } from "./vault";
import { mailchimpManifest } from "../../lib/data/mailchimp";

/** The four status files are a partition — no address appears in two of them. */
const STATUS_FILES = {
  subscribed: "subscribed_email_audience_export_1a10653875.csv",
  unsubscribed: "unsubscribed_email_audience_export_1a10653875.csv",
  cleaned: "cleaned_email_audience_export_1a10653875.csv",
  nonsubscribed: "nonsubscribed_email_audience_export_1a10653875.csv",
} as const;

function requireVault(exportId: string) {
  if (!vaultExists(exportId)) {
    console.error(
      `This script needs the raw export. Vault not found for ${exportId}.\n` +
        `  Set MAILCHIMP_VAULT_DIR or place the CSVs in private/mailchimp/${exportId}/.\n` +
        `  The committed archive holds per-YEAR aggregates only; a half-year figure\n` +
        `  has to be read off the row timestamps, which are never committed.`
    );
    process.exit(1);
  }
}

/**
 * Mailchimp writes `2026-04-14 09:12:33` — lexicographically ordered, so a
 * string compare against an ISO date is exact and needs no Date parsing.
 * An empty cell must never fall inside the window; hence the explicit guard.
 */
function within(value: string | undefined, from: string, to: string): boolean {
  const stamp = String(value ?? "").trim();
  if (!stamp) return false;
  return stamp >= from && stamp <= `${to} 23:59:59`;
}

function monthOf(value: string | undefined): string {
  return String(value ?? "").slice(0, 7);
}

function tally(values: string[]): Map<string, number> {
  const out = new Map<string, number>();
  for (const value of values) out.set(value, (out.get(value) ?? 0) + 1);
  return out;
}

function main() {
  const argv = process.argv.slice(2);
  const from = argValue(argv, "--from") ?? "2026-01-01";
  const to = argValue(argv, "--to") ?? "2026-06-30";
  const exportId =
    argValue(argv, "--export") ?? mailchimpManifest.exports.at(-1)?.exportId ?? "";

  requireVault(exportId);

  const subscribed = readCsv(exportId, STATUS_FILES.subscribed);
  const unsubscribed = readCsv(exportId, STATUS_FILES.unsubscribed);
  const cleaned = readCsv(exportId, STATUS_FILES.cleaned);
  const nonsubscribed = readCsv(exportId, STATUS_FILES.nonsubscribed);

  const lines: string[] = [];
  const say = (text = "") => lines.push(text);
  const note = (text: string) => `"${text.replace(/"/g, '\\"')}"`;

  const source = `the Mailchimp audience export ${exportId} (private/mailchimp/${exportId}/, hashes in lib/data/json/mailchimp/manifest.json)`;

  say(`// Mailchimp figures for ${from} .. ${to}`);
  say(`// Generated by scripts/mailchimp/report-metrics.ts from export ${exportId}.`);
  say(`//`);
  say(`// PASTE, DO NOT PIPE. Every v() note is a claim somebody signs.`);
  say();

  // ── The standing list ──────────────────────────────────────────────────────
  const emailable = subscribed.length;
  const lifetime =
    subscribed.length + unsubscribed.length + cleaned.length + nonsubscribed.length;

  say("// ---- the standing list ----");
  say(`newsletter-subscribers: v(`);
  say(`  ${emailable},`);
  say(
    `  ${note(`Contacts in the She# Mailchimp audience with status "subscribed" — the people who may lawfully be emailed. Read at the export date, ${exportId}, not at ${to}: Mailchimp exports a snapshot of the present, and the status column carries no history. The audience holds ${lifetime} contacts in total; the other ${lifetime - emailable} unsubscribed, hard-bounced, or never subscribed, and are suppression-hashed in lib/data/json/email-suppression-hashes.json so no future import can re-add them. Source: ${source}.`)},`
  );
  say(`),`);
  say();

  // ── The half-year flow ─────────────────────────────────────────────────────
  //
  // Standing totals hide direction. A list that grew by 200 and a list that
  // shrank by 200 both report the same number on the last day of the period.
  const joined = subscribed.filter((row) => within(row["OPTIN_TIME"], from, to));
  const left = unsubscribed.filter((row) => within(row["UNSUB_TIME"], from, to));
  const bounced = cleaned.filter((row) => within(row["CLEAN_TIME"], from, to));
  const net = joined.length - left.length - bounced.length;

  say("// ---- the half-year flow ----");
  say(`newsletter-joined: v(`);
  say(`  ${joined.length},`);
  say(
    `  ${note(`Contacts whose OPTIN_TIME falls in ${from}..${to} and who were still subscribed at the export date. Source: ${source}.`)},`
  );
  say(`),`);
  say(`newsletter-unsubscribed: v(`);
  say(`  ${left.length},`);
  say(
    `  ${note(`Contacts whose UNSUB_TIME falls in ${from}..${to}. Source: ${source}.`)},`
  );
  say(`),`);
  say(`newsletter-bounced: v(`);
  say(`  ${bounced.length},`);
  say(
    `  ${note(`Contacts whose CLEAN_TIME falls in ${from}..${to} — addresses Mailchimp removed after a hard bounce. These are undeliverable mailboxes, not people choosing to leave. Source: ${source}.`)},`
  );
  say(`),`);
  say(`newsletter-net: v(`);
  say(`  ${net},`);
  say(
    `  ${note(`${joined.length} joined less ${left.length} unsubscribed and ${bounced.length} removed as undeliverable, ${from}..${to}. Source: ${source}.`)},`
  );
  say(`),`);
  say();

  say(`// joins by month:   ${[...tally(joined.map((r) => monthOf(r["OPTIN_TIME"]))).entries()].sort().map(([k, v]) => `${k}=${v}`).join(" ")}`);
  say(`// unsubs by month:  ${[...tally(left.map((r) => monthOf(r["UNSUB_TIME"]))).entries()].sort().map(([k, v]) => `${k}=${v}`).join(" ")}`);
  say(`// bounces by month: ${[...tally(bounced.map((r) => monthOf(r["CLEAN_TIME"]))).entries()].sort().map(([k, v]) => `${k}=${v}`).join(" ")}`);
  say();

  // ── Campaigns evidenced as sent ────────────────────────────────────────────
  //
  // A campaign appears here only if at least one recipient unsubscribed from it
  // or bounced on it. That makes every count below a FLOOR. It also makes the
  // window unsafe for OLD campaigns: a 2024 event email can collect an
  // unsubscribe in 2026, and its title would then look like a 2026 send. Only
  // titles that DATE THEMSELVES inside the window are quoted as evidence.
  // Date each campaign by its EARLIEST reaction anywhere in the export, not by
  // its title and not by a reaction inside the window. A 2024 event email can
  // collect an unsubscribe in 2026, and filtering on the window alone would
  // read that as a 2026 send. The earliest reaction is an upper bound on the
  // send date, and it is the only send date this export carries at all.
  const year = from.slice(0, 4);
  const firstReaction = new Map<string, string>();
  const bump = (title: string, stamp: string) => {
    const name = title.trim();
    const when = stamp.trim();
    if (!name || !when) return;
    const seen = firstReaction.get(name);
    if (!seen || when < seen) firstReaction.set(name, when);
  };
  for (const row of unsubscribed) {
    bump(String(row["UNSUB_CAMPAIGN_TITLE"] ?? ""), String(row["UNSUB_TIME"] ?? ""));
  }
  for (const row of cleaned) {
    bump(String(row["CLEAN_CAMPAIGN_TITLE"] ?? ""), String(row["CLEAN_TIME"] ?? ""));
  }

  const sentInWindow = [...firstReaction]
    .filter(([, stamp]) => within(stamp, from, to))
    .sort((a, b) => a[1].localeCompare(b[1]));

  const newsletters = sentInWindow.filter(([title]) => /newsletter/i.test(title));
  const eventEmails = sentInWindow.filter(([title]) => !/newsletter/i.test(title));

  say("// ---- campaigns evidenced as sent in the window ----");
  say(`// A campaign appears in this export only when at least one recipient`);
  say(`// unsubscribed from it or bounced on it. Every count below is a FLOOR.`);
  say(`// Dated by earliest reaction, which is an upper bound on the send date.`);
  say(`//`);
  say(`// Newsletter issues (${newsletters.length}):`);
  for (const [title, stamp] of newsletters) say(`//   ${stamp}  ${title}`);
  say(`// Event and campaign emails (${eventEmails.length}):`);
  for (const [title, stamp] of eventEmails) say(`//   ${stamp}  ${title}`);
  say();
  say(`newsletter-issues: v(`);
  say(`  ${newsletters.length},`);
  say(
    `  ${note(`Monthly newsletter issues evidenced as sent between ${from} and ${to}: ${newsletters.map(([title]) => title).join("; ")}. Mailchimp records the campaign a contact unsubscribed from and the campaign a hard bounce was detected on; each issue here is dated by the earliest such reaction, which is an upper bound on its send date. A campaign nobody left and nobody bounced on would be invisible, so this is a FLOOR, not a count of sends — but it IS a record of sends, which lib/newsletter/schedule.ts is not: that file computes a send slot. No January or February ${year} issue appears anywhere in the record. Source: ${source}.`)},`
  );
  say(`),`);
  say(`event-email-campaigns: v(`);
  say(`  ${eventEmails.length},`);
  say(
    `  ${note(`Distinct non-newsletter campaigns evidenced as first sent between ${from} and ${to}: ${eventEmails.map(([title]) => title).join("; ")}. Same floor and same dating rule as the issue count above. Source: ${source}.`)},`
  );
  say(`),`);
  say();

  // ── Location, stated with its hole ─────────────────────────────────────────
  const withCountry = subscribed.filter((row) => String(row["CC"] ?? "").trim());
  const countries = tally(
    withCountry.map((row) => String(row["CC"]).trim().toLowerCase())
  );
  const regions = tally(
    subscribed
      .map((row) => String(row["REGION"] ?? "").trim().toLowerCase())
      .filter(Boolean)
  );

  say("// ---- location ----");
  say(
    `// ${subscribed.length - withCountry.length} of ${subscribed.length} subscribed contacts (${Math.round(((subscribed.length - withCountry.length) / subscribed.length) * 100)}%) carry NO country.`
  );
  say(`// Any geographic claim must name that before it names a place.`);
  say(
    `// countries: ${[...countries].sort((a, b) => b[1] - a[1]).slice(0, 6).map(([k, v]) => `${k}=${v}`).join(" ")}`
  );
  say(
    `// regions:   ${[...regions].sort((a, b) => b[1] - a[1]).slice(0, 6).map(([k, v]) => `${k}=${v}`).join(" ")}`
  );
  say();

  const outDir = join(REPO_ROOT, "tmp", "mailchimp");
  mkdirSync(outDir, { recursive: true });
  const path = join(outDir, "report-data-suggestions.typ");
  writeFileSync(path, lines.join("\n") + "\n", "utf8");

  console.log(`Wrote ${path}`);
  console.log(`  window            ${from} .. ${to}`);
  console.log(`  emailable now     ${emailable}  (at export ${exportId})`);
  console.log(`  joined            ${joined.length}`);
  console.log(`  unsubscribed      ${left.length}`);
  console.log(`  bounced out       ${bounced.length}`);
  console.log(`  net               ${net}`);
  console.log(`  newsletter issues ${newsletters.length}  (floor)`);
  console.log("\nNothing under report/ was written.");
}

main();
